### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by pieroandreini** [LionSec/xerosploit#101]
Same issue on raspberry pi2 (Kali 3.2) and Nexus5 (Kali Nethunter 3.2)

┌═════════════════════════════════════════════════════════════════════════════┐
█                                                                             █
█                         Your Network Configuration                          █ 
█                                                                             █
└═════════════════════════════════════════════════════════════════════════════┘     
 
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 980, in main
    home()
  File "/opt/xerosploit/xerosploit.py", line 89, in home
    print (tabulate(table, stralign="center",tablefmt="fancy_grid",headers="firstrow"))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-78: ordinal not in range(128)

Already tried but did not help:

# encoding=utf8
import sys
reload(sys)
sys.setdefaultencoding('utf8')

**Comment by quartz010** [comment]
I got the same problem.

**Comment by pfftdammitchris** [comment]
Read the fix at: #88

**Comment by quartz010** [comment]
thx!

**Comment by dakshkhurana** [comment]
I got same problem how to solve bro tell me plz

**Comment by aladdinsparta** [comment]
Traceback (most recent call last):
  File "xerosploit.py", line 980, in main
    home()
  File "xerosploit.py", line 89, in home
    print (tabulate(table, stralign="center",tablefmt="fancy_grid",headers="firstrow"))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-72: ordinal not in range(128)
[aladdinx@aladdinx ~]$ 
 arch linux ??
