### ISSUE TITLE
ImportError: No module named terminaltables

### ISSUE THREAD

**Issue by EslamElsaidi** [LionSec/xerosploit#102]
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable

**Comment by VERAN-HM** [comment]
pip install tabulate
try this command friend and id3ilna  m3ak

**Comment by Emberborne** [comment]
Not working even after this command :(

**Comment by larry852** [comment]
Try: 
python2.7 /usr/bin/pip install terminaltables
python2.7 /usr/bin/pip install tabulate
python2.2 /opt/xerosploit/xerosploit.py

**Comment by An0nUD4Y** [comment]
Its working Thanks... @larry852

**Comment by Bipslove** [comment]
root@kali:~# xerosploit
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables

**Comment by Bipslove** [comment]
plz.... help to solve this problem in xerosploit

**Comment by marbyn** [comment]
help to solve this problem in xerosploit

**Comment by hamidule6** [comment]
Tell me what can I help you.

**Comment by Squiddlle** [comment]
python2.7 /usr/local/bin/pip install terminaltables

**Comment by Irmawanto** [comment]
l found the solution for error install xerosploit 
 
pip install terminal tables
pip install tabulate
 
and if you already install everything 
install xerosploit again and open the xerosploit enjoy the xerosploit

**Comment by bacaham22** [comment]
Alguien me puede ayudar no encuentro la solución ayuden 
root @ kali: ~ # xerosploit
Traceback (última llamada más reciente):
Archivo "/opt/xerosploit/xerosploit.py", línea 26,
desde terminaltables import DoubleTable
ImportError: Ningún módulo llamado terminaltables

**Comment by Ebby-crypto** [comment]
@larry852 thk u that worked

**Comment by alvin710** [comment]
I think you are suppose to type in Terminal “from terminaltables import DoubleTable“

**Comment by misbagas** [comment]
hey @larry852  
why No such file or directory of my file 

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/usr/bin/pip': [Errno 2] No such file or directory

anyone please help me

**Comment by LightC0der** [comment]
Its because you have installed the modules for python2 but you're executing the file on python3. 
Do this; 
/usr/bin/pip3 install terminaltable
/usr/bin/pip3 install tabulate

**Comment by osamabasem** [comment]
i have same problem that say .... when i write xerosploit
tracekback (most recent call last):
file "/opt/xerosploit/xerosploit.py", line 26, in <module>
from terminaltables import DoubleTables
ImportError: no module named terminaltables

**Comment by osamabasem** [comment]
> i have same problem that say .... when i write xerosploit
> tracekback (most recent call last):
> file "/opt/xerosploit/xerosploit.py", line 26, in
> from terminaltables import DoubleTables
> ImportError: no module named terminaltables

i want solve please

**Comment by ekovegeance** [comment]
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables


----------------------------------------------------------------------
on Kali Linux 2020

**Comment by deadsince** [comment]
Traceback (most recent call last):
  File "xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables

**Comment by deadsince** [comment]
> Its because you have installed the modules for python2 but you're executing the file on python3.
> Do this;
> /usr/bin/pip3 install terminaltable
> /usr/bin/pip3 install tabulate

ERROR: Could not find a version that satisfies the requirement terminaltable (from versions: none)
ERROR: No matching distribution found for terminaltable

**Comment by parinavcodes** [comment]
Terminaltables at the point of this comment, supports these versions: Python 2.6, 2.7, PyPy, PyPy3, 3.3, 3.4, and 3.5 supported on Linux and OS X.
Python 2.7, 3.3, 3.4, and 3.5 supported on Windows (both 32 and 64 bit versions of Python).

**Comment by adinesh590** [comment]
> Try:
> python2.7 /usr/bin/pip install terminaltables
> python2.7 /usr/bin/pip install tabulate
> python2.7 /opt/xerosploit/xerosploit.py

Traceback (most recent call last):
  File "/usr/bin/pip", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==20.1.1' distribution was not found and is required by the application




help, please!!!!!!!!!!!

**Comment by HUNTERBUNNY303** [comment]
> Traceback (most recent call last):
> File "/opt/xerosploit/xerosploit.py", line 26, in
> from terminaltables import DoubleTable

This video clears all errors https://youtu.be/_1KpQ0hYeVw

**Comment by HUNTERBUNNY303** [comment]
100%

**Comment by Kaushal-art** [comment]
Try

Inside xerosploit.py file replace the following line as given below

from terminaltables import DoubleTable

with

from terminaltables.other_tables import DoubleTable

I faced the same problem after this the problem is solved...
Thanks may this solve yours problem

**Comment by RTMN369** [comment]
el video que compartio HUNTERBUNNY303  funciona perfectamente graciass

**Comment by rockydipsy** [comment]
pip install -t /usr/lib/python2.7/dist-packages/ terminaltables
pip install -t /usr/lib/python2.7/dist-packages/ tabulate

**Comment by okcoder2019** [comment]
I got it working with python3.8 xerosploit.py

**Comment by tboy-hacker** [comment]
guy stop fighting for something easy like go to this link      https://chowdera.com/2021/12/202112112325476349.html

**Comment by Apoloyon** [comment]
> > Traceback (most recent call last):
> > File "/opt/xerosploit/xerosploit.py", line 26, in
> > from terminaltables import DoubleTable
> 
> This video clears all errors https://youtu.be/_1KpQ0hYeVw

Yea this works

**Comment by Ayanjjj** [comment]
sudo apt install 2to3
pip3 install 2to3
sudo 2to3 -W install.py
sudo python3 install.py
sudo 2to3 -W xerosploit.py
sudo python3 xerosploit.py

**Comment by halqadasi** [comment]
> pip install terminal tables
> pip install tabulate

this solution worked with me but without space between termianl and table: `terminaltables`
