### ISSUE TITLE
Xerosploit Not working

### ISSUE THREAD

**Issue by Kum4r4n** [LionSec/xerosploit#109]
Http website work good.  But https websites didnt work.  Ex- google facebook. And driftnet google images not showing in driftnet window.  Another one replace image dosent work for me. Plz help.

**Comment by karami53f** [comment]
upt-get dist-upgrade

**Comment by Francesco73** [comment]
buonasera i have a problem please help me
[++] Injecting Html code ... 

[++] Press 'Ctrl + C' to stop . 

/usr/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate': undefined method `activate' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /var/lib/gems/2.3.0/gems/xettercap-1.5.7xerob/bin/xettercap:16:in `<top (required)>'
	from /usr/local/bin/xettercap:22:in `load'
	from /usr/local/bin/xettercap:22:in `<main>'

[+] Enter 'run' to execute the 'injecthtml' command.
What is this problem,thanks.

**Comment by Flow44A** [comment]
Try: sudo gem install sorted_set
