### ISSUE TITLE
trity error

### ISSUE THREAD

**Issue by mohdtariq7878** [LionSec/xerosploit#111]
sir when i start the trity so it shows the error
which is :traceback (most recen call last)
file "/opt/trity/trity.py", line 27,in <module > from search import *
file "opt/trity/trity.py", line 1 in <module> from google import search 
importerror: no module named google
how can i fix it plzz give me complete commad

**Comment by SergioLeiva** [comment]
Before you run install.py you have to change the line in install.py : 
os.system('pip install google') -> os.system('pip install search_google')

**Comment by f3max** [comment]
i add this os.system('pip install search_google').. but not fix.. 

then i check error..  
file "/opt/trity/trity.py", line 27,in from search import *
file "opt/trity/search.py", line 1 in from google import search

i remove that line.. from google import search .. then add ->  import search_google 
that worked...

sorry for my bad english

**Comment by jedi1010** [comment]
I have a problem. Import error: no module named qrcode. While running ./ run.sh in trity please help...

**Comment by r4jr** [comment]
When I run trity it says "You don't have some modules installed!
Please run install.py to install this tool fully!" what I do?

**Comment by fabi-mu** [comment]
I run trity:

cat: /sys/class/net/eth0/address: Datei oder Verzeichnis nicht gefunden
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 15, in <module>
    from twitter import *
  File "/opt/trity/twitter.py", line 3, in <module>
    from bs4 import BeautifulSoup as So
ImportError: No module named bs4

pls help me

**Comment by BloodITA** [comment]
I run trity:

root@DESKTOP-FLG6824:~# trity
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 7, in <module>
    sys.path.append('trity/')
NameError: name 'sys' is not defined

How can I fix it?

**Comment by McDEEZX** [comment]
Please I need help...
     Traceback (most recent call last):
  File "/opt/trity/trity.py", line 13, in <module>
    from info import *
  File "/opt/trity/info.py", line 17, in <module>
    s.connect(('google.com', 0))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.gaierror: [Errno -2] Name or service not known

    How can I fix it ?

**Comment by shahibu** [comment]
https://stackoverflow.com/a/57227144/11843192

**Comment by max0999** [comment]
La solution  :

pip install twitter
pip install qrcode

et éditer comme suis  :  

cd trity

nano searchs.py

from googlesearch import search
class color:
   OKGREEN = '\033[92m'
   WARNING = '\033[93m'
   FAIL = '\033[91m'
   UNDERLINE = '\033[4m'
   END = '\033[0m'
   ENDC = '\033[0m'
W  = '\033[0m'  # white (normal)
R  = '\033[31m' # red
G  = '\033[32m' # green
O  = '\033[33m' # orange
B  = '\033[34m' # blue
P  = '\033[35m' # purple
C  = '\033[36m' # cyan
T  = '\033[93m' # tan
M = '\033[1;35;32m' # magenta
def googleSearch():
    lol = raw_input(color.UNDERLINE + ""+T+"Query>" + color.END)
    for url in search(lol, tld='com', lang='fr', stop=50):
            print(url)

Save, et cd .. --->> python trity.py

**Comment by toxiczone** [comment]
Traceback (most recent call last):
  File "/opt/trity/trity.py", line 14, in <module>
    from anon import *
  File "/opt/trity/anon.py", line 1, in <module>
    import mechanize
ImportError: No module named mechanize
