### ISSUE TITLE
lots of error (parrot OS 3.x)

### ISSUE THREAD

**Issue by tehseensagar** [LionSec/xerosploit#13]
█
█                        Deface Web Page                       █
█                                                              █
█        Overwrite all web pages with your HTML code           █
└══════════════════════════════════════════════════════════════┘     

[+] Enter 'run' to execute the 'deface' command.

Xero»modules»deface ➮ run

[+] Specify the file containing your defacement code .

[!] Your file should not contain Javascript code .

Xero»modules»deface ➮ '/root/f.html' 
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/opt/xerosploit/xerosploit.py", line 869, in cmd0
    scan()
  File "/opt/xerosploit/xerosploit.py", line 129, in scan
    target_ip()
  File "/opt/xerosploit/xerosploit.py", line 855, in target_ip
    program0()
  File "/opt/xerosploit/xerosploit.py", line 829, in program0
    option()
  File "/opt/xerosploit/xerosploit.py", line 825, in option
    option()
  File "/opt/xerosploit/xerosploit.py", line 828, in option
    option()
  File "/opt/xerosploit/xerosploit.py", line 784, in option
    deface()
  File "/opt/xerosploit/xerosploit.py", line 766, in deface
    file_deface  = open(file_deface, 'r').read()
IOError: [Errno 2] No such file or directory: '/root/f.html '

Ive tried different module even just inject html file , it gives same error over wifi.

Regards
Scorpoin

**Comment by LionSec** [comment]
Please be sure that there is no white space when you set the file location . Regards

**Comment by tehseensagar** [comment]
I ran dos2unix incase if there is any white space in code:

Xero»modules ➮ deface
 
┌══════════════════════════════════════════════════════════════┐
█                                                              █
█                        Deface Web Page                       █
█                                                              █
█        Overwrite all web pages with your HTML code           █
└══════════════════════════════════════════════════════════════┘     

[+] Enter 'run' to execute the 'deface' command.

Xero»modules»deface ➮ run

[+] Specify the file containing your defacement code .

[!] Your file should not contain Javascript code .

Xero»modules»deface ➮ '/root/f.html'

[++] Overwriting all web pages ... 

[++] Press 'Ctrl + C' to stop . 

Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/opt/xerosploit/xerosploit.py", line 869, in cmd0
    scan()
  File "/opt/xerosploit/xerosploit.py", line 129, in scan
    target_ip()
  File "/opt/xerosploit/xerosploit.py", line 855, in target_ip
    program0()
  File "/opt/xerosploit/xerosploit.py", line 829, in program0
    option()
  File "/opt/xerosploit/xerosploit.py", line 825, in option
    option()
  File "/opt/xerosploit/xerosploit.py", line 784, in option
    deface()
  File "/opt/xerosploit/xerosploit.py", line 774, in deface
    f1 = open('/home/home/xero-html.html','w')
IOError: [Errno 2] No such file or directory: '/home/home/xero-html.html'


still getting error. Ive written a simple html page hello world .

**Comment by jeretc** [comment]
Hi i face the same issue when using the "replace" module.

**Comment by tehseensagar** [comment]
@LionSec plz update and help me out how to resolve this issue.

**Comment by LionSec** [comment]
Hello try using a relative path . Xerosploit's location is : /opt/xerosploit/ . More info : http://www.linuxnix.com/abslute-path-vs-relative-path-in-linuxunix/

**Comment by samupert** [comment]
@tehseensagar @LionSec 

I fixed the problem creating the file xero-html.html
xero-html.html was missing in the dir '/home/home/'

Launch these lines
`
cd /home
sudo mkdir home
cd home
sudo echo "" >  xero-html.html
`
