### ISSUE TITLE
installed xerosploit in kali linux rpi

### ISSUE THREAD

**Issue by jiroseichi** [LionSec/xerosploit#15]
i got the following error after installing xerosploit

root@kali:/xerosploit/xerosploit# ./xerosploit.py 
Traceback (most recent call last):
  File "./xerosploit.py", line 980, in main
    home()
  File "./xerosploit.py", line 62, in home
    config0()
  File "./xerosploit.py", line 44, in config0
    up_interface = open('/opt/xerosploit/tools/files/iface.txt', 'r').read()
IOError: [Errno 2] No such file or directory: '/opt/xerosploit/tools/files/iface.txt'

pls help. thanks!

**Comment by wallyssonlima** [comment]
run the following commands in your terminal:
   git clone https://github.com/LionSec/xerosploit
   cd xerosploit && sudo python install.py
   sudo xerosploit

install the dependencies:
   sudo apt install pip
   sudo pip install tabulate
   sudo pip install terminaltables

**Comment by varthdader** [comment]
I faced this same issue on the Raspberry running Kali. 

I edited all the lines with.
     print(table.table)

To the following.
     print(table.table).encode('utf-8')

Now all UnicodeEncodeErrors seem to be gone.

**Comment by gl1dd3r** [comment]
Neither of the suggestions did anything for me. I still get the same error:

Traceback (most recent call last):
File "./xerosploit.py", line 980, in main
home()
Traceback (most recent call last):
File "./xerosploit.py", line 98, in home
Print (tabulate(table, straling="center" ,tablefmt=fancy_grid",headers="firstrow"))
UnicodeEncodeError: 'ascii' codec cant encode  characters in possition 0-77: ordinal not in range (128)

**Comment by Liljhon241** [comment]
After installing terminaltables and tabulate by running pip install terminaltables and pip install tabulate go to /usr/local/lib/python3.5/dist-packages copy and paste terminaltables and tabulate in the xerosploit directory then run xerosploit in the terminal (sorry for my bad english)
It work for me

**Comment by unknownbatman** [comment]
guys it is very simple just rename the xerosploit-master directory to xerosploit only

**Comment by pfftdammitchris** [comment]
Head on over to #88

**Comment by Arifbhat** [comment]
Guys I have same problem today.

**Comment by techsiwolof** [comment]
Just go to xerosploit folder. Edit the install.py file by replacing "python-pip" with "python3-pip". Then run "sudo python install.py".
