### ISSUE TITLE
'ascii' codec can't encode characters in position 0-70: ordinal not in range(128)

### ISSUE THREAD

**Issue by baidak-d** [LionSec/xerosploit#154]
I launch the program through ssh. x11

```
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 980, in main
    home()
  File "/opt/xerosploit/xerosploit.py", line 89, in home
    print (tabulate(table, stralign="center",tablefmt="fancy_grid",headers="firstrow"))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-70: ordinal not in range(128)
```

**Comment by haroonalhadisk** [comment]
This is not fixed yet.  Even though developer claims it to be as I am getting the exact same error.
