### ISSUE TITLE
 File "/opt/xerosploit/xerosploit.py", line 26

### ISSUE THREAD

**Issue by naimkowshik** [LionSec/xerosploit#169]
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables

**Comment by emads556** [comment]
Do you know how to fix this issue?

**Comment by SipriusPT** [comment]
Same issue here with kali 4.18.0-kali2-amd64

**Comment by caseykey** [comment]
Same issue here on Kali rolling 2020.1

**Comment by Fato07** [comment]
Same issue here on kalilinux/kali-rolling docker image container when trying to install xerosploit

**Comment by KeakaR** [comment]
Same issue here Kali-Linux 2022 after installation
