### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/opt/xerosploit/tools/files/iface.txt' got a issue how to fix?

### ISSUE THREAD

**Issue by amykimm** [LionSec/xerosploit#175]
Hi, I got an issue, showing me that 

Traceback (most recent call last):
  File "./xerosploit.py", line 980, in main
    home()
  File "./xerosploit.py", line 62, in home
    config0()
  File "./xerosploit.py", line 44, in config0
    up_interface = open('/opt/xerosploit/tools/files/iface.txt', 'r').read()
IOError: [Errno 2] No such file or directory: '/opt/xerosploit/tools/files/iface.txt'

how can I fix this ?

**Comment by minkyman-coding101** [comment]
>> "sudo make install"

This will copy the files over :)

**Comment by nightingale-python** [comment]
Thanks, thanks, thanks. I've worked so hard for this. I am very happy.

**Comment by putinshairline** [comment]
Thank you so much! works like a charm!
Very happy

**Comment by Hazzanawarafik** [comment]
work thank you

**Comment by Ep262626** [comment]
What’s this for

Eric
________________________________

**Comment by AvinFajarF** [comment]
> > sudo make install
> 
> This will copy the files over :)

thanks bro
