### ISSUE TITLE
cannot run the tool

### ISSUE THREAD

**Issue by azamet90** [LionSec/xerosploit#183]
sudo xerosploit

____  __                     ________         ______       _____ _____ 
__  |/ /_____ ______________ __  ___/________ ___  /______ ___(_)__  /_
__    / _  _ \__  ___/_  __ \_____ \ ___  __ \__  / _  __ \__  / _  __/
_    |  /  __/_  /    / /_/ /____/ / __  /_/ /_  /  / /_/ /_  /  / /_  
/_/|_|  \___/ /_/     \____/ /____/  _  .___/ /_/   \____/ /_/   \__/  
                                     /_/                                    

[+]═══════════[ Author : @LionSec1 _-\|/-_ Website: www.neodrix.com ]═══════════[+]

                      [ Powered by Bettercap and Nmap ]
 
┌═════════════════════════════════════════════════════════════════════════════┐
█                                                                             █
█                         Your Network Configuration                          █ 
█                                                                             █
└═════════════════════════════════════════════════════════════════════════════┘     
 
╒═══════════════╤═══════════════════╤══════════════╤═════════╤════════════╕
│  IP Address   │    MAC Address    │   Gateway    │  Iface  │  Hostname  │
╞═══════════════╪═══════════════════╪══════════════╪═════════╪════════════╡
├───────────────┼───────────────────┼──────────────┼─────────┼────────────┤
│ 192.168.43.39 │ 0C:DD:24:2A:FF:76 │ 192.168.43.1 │  wlan0  │ localhost  │
╘═══════════════╧═══════════════════╧══════════════╧═════════╧════════════╛

╔═════════════╦════════════════════════════════════════════════════════════════════╗
║             ║ XeroSploit is a penetration testing toolkit whose goal is to       ║
║ Information ║ perform man in the middle attacks for testing purposes.            ║
║             ║ It brings various modules that allow to realise efficient attacks. ║
║             ║ This tool is Powered by Bettercap and Nmap.                        ║
╚═════════════╩════════════════════════════════════════════════════════════════════╝

[+] Please type 'help' to view commands.

Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/opt/xerosploit/xerosploit.py", line 866, in cmd0
    cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip()
NameError: name 'raw_input' is not defined

**Comment by azamet90** [comment]
looks like no more support for this tool if 150 issues is open no one is closed this is what i understand if a user can help me will very good actually

**Comment by jaredliw** [comment]
I think you havent install python2, have you?

**Comment by azamet90** [comment]
> I think you havent install python2, have you?

of course i have installed it

**Comment by abdo743dotcom** [comment]
Traceback (most recent call last):
	3: from /usr/local/bin/xettercap:23:in `<main>'
	2: from /usr/local/bin/xettercap:23:in `load'
	1: from /var/lib/gems/2.5.0/gems/xettercap-1.5.7xerob/bin/xettercap:24:in `<top (required)>'
/var/lib/gems/2.5.0/gems/xettercap-1.5.7xerob/bin/xettercap:51:in `rescue in <top (required)>': undefined local variable or method `original_argv' for main:Object (NameError)

**Comment by jm2monkeyking** [comment]
You should **move** the **file** to the **/opt** directory

**Comment by vapemx** [comment]
@azamet90 that error happens for the python2 python3 mess. You must to change the all `raw_input` for just `input` in xerosploit.py
