### ISSUE TITLE
How to fix this

### ISSUE THREAD

**Issue by Jaya0356** [LionSec/xerosploit#199]
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 980, in main
    home()
  File "/opt/xerosploit/xerosploit.py", line 89, in home
    print (tabulate(table, stralign="center",tablefmt="fancy_grid",headers="firstrow"))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-72: ordinal not in range(128)

**Comment by Jaya0356** [comment]
PLS
