### ISSUE TITLE
NameError: name 'raw_input' is not defined

### ISSUE THREAD

**Issue by leodagiman** [LionSec/xerosploit#202]
Traceback (most recent call last):
  File "install.py", line 65, in <module>
    main()
  File "install.py", line 45, in main
    system0 = raw_input(">>> ")
NameError: name 'raw_input' is not defined

**Comment by hasanpasha** [comment]
try this it should work:
`sudo python2 install.py`

**Comment by GosulaShivaKumar** [comment]
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/opt/xerosploit/xerosploit.py", line 866, in cmd0
    cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip()
NameError: name 'raw_input' is not defined
this is my error

**Comment by zaigonHack** [comment]
Delete raw_ leave only input, in all lines where raw_input is

**Comment by Cyber-Warrior-6** [comment]
@zaigonHack Thanks Bro.

**Comment by jainammutha** [comment]
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/opt/xerosploit/xerosploit.py", line 866, in cmd0
    cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip()
NameError: name 'raw_input' is not defined

**Comment by davcwikla** [comment]
> Otwórz plik xerosploit.py za pomocą edytora i usuń raw_, zostaw tylko dane wejściowe, we wszystkich wierszach, w których znajduje się raw_input

Not working for me...

**Comment by Gunes00** [comment]
> try this it should work: `sudo python2 install.py`

thanks
