### ISSUE TITLE
E: Unable to locate package python-terminaltables

### ISSUE THREAD

**Issue by tayyab2000** [LionSec/xerosploit#206]
i had tried pip install terminaltables and pip3 install tabulate but i am  still getting an error .
CAN YOU PLEASE HELP ME HOW TO FIX IT ?

[++] Please choose your operating system.

1) Ubuntu / Kali linux / Others
2) Parrot OS

>>> 2

[++] Installing Xerosploit ... 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'bettercap' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Successfully installed bettercap-1.6.2
Parsing documentation for bettercap-1.6.2
Done installing documentation for bettercap after 7 seconds
1 gem installed
Hit:1 https://deb.parrot.sh/parrot rolling InRelease
Hit:2 https://deb.parrot.sh/parrot rolling-security InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-terminaltables
WARNING:  bin/xettercap is not executable
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: xettercap
  Version: 1.5.7xerob
  File: xettercap-1.5.7xerob.gem
Successfully installed xettercap-1.5.7xerob
Parsing documentation for xettercap-1.5.7xerob
Done installing documentation for xettercap after 3 seconds
1 gem installed
Xerosploit has been sucessfuly instaled. Execute 'xerosploit' in your terminal.
┌─[root@parrot]─[~/Desktop/xerosploit]
└──╼ #xerosploit
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 27, in <module>
    from tabulate import tabulate
ImportError: No module named tabulate

**Comment by Ubunkali** [comment]
pip install tabulate for  python 1 python2 pip2 install tabulate terminaltables, only issue you can install however I am yet to get any of the modules to actually work?? Why no one out here will offer any insight to as of why gets me???

**Comment by tayyab2000** [comment]
THANKS BRO ! 
i changed python-terminaltables to python3-terminaltables from xerosploit install.py in line 48 ( for kali linux ) or in line 57 (for parrot os )
then install xerosploit and it's work well :)

**Comment by EAAGTeam** [comment]
You need to edit the file install.py and replace the las 3 "python" by "python3"

**Comment by DaoudPro** [comment]
I replaced "python" by "python3" but it's not working

Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/opt/xerosploit/xerosploit.py", line 866, in cmd0
    cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip()
NameError: name 'raw_input' is not defined

**Comment by ekko231** [comment]
replace "python" by "python3" but don't run it with python3 run it with python2 it should work
