### ISSUE TITLE
replace image isnt working plz check out the problem and try to resolve it

### ISSUE THREAD

**Issue by devrajashwin** [LionSec/xerosploit#211]
Enter 'run' to execute the 'replace' command.                          
                                                                           
Xero»modules»replace ➮ run

[+] Insert your image path. (e.g. /home/capitansalami/pictures/fun.png)    
                                                                           
Xero»modules»replace ➮ /root/Pictures/IMG_0197.JPG
Traceback (most recent call last):
  File "./xerosploit.py", line 981, in main
    cmd0()
  File "./xerosploit.py", line 869, in cmd0
    scan()
  File "./xerosploit.py", line 129, in scan
    target_ip()
  File "./xerosploit.py", line 855, in target_ip
    program0()
  File "./xerosploit.py", line 829, in program0
    option()
  File "./xerosploit.py", line 825, in option
    option()
  File "./xerosploit.py", line 635, in option
    replace()
  File "./xerosploit.py", line 621, in replace
    from PIL import Image
ImportError: No module named PIL

**Comment by itartinas** [comment]
sameeeee probleem did you fixed that?

**Comment by devrajashwin** [comment]
No idont have puss permission anf the code is still fusy

**Comment by s1l3nt3rf** [comment]
try ...

sudo apt-get install python-pil
