### ISSUE TITLE
HI please help

### ISSUE THREAD

**Issue by itartinas** [LionSec/xerosploit#218]
sudo python3 install.py
 
┌══════════════════════════════════════════════════════════════┐
█                                                              █
█                     Xerosploit Installer                     █
█                                                              █
└══════════════════════════════════════════════════════════════┘     

[++] Please choose your operating system.

1) Ubuntu / Kali linux / Others
2) Parrot OS

Traceback (most recent call last):
  File "install.py", line 65, in <module>
    main()
  File "install.py", line 45, in main
    system0 = raw_input(">>> ")
NameError: name 'raw_input' is not defined

**Comment by umeshgain** [comment]
use python2 instead of python3

**Comment by umeshgain** [comment]
**python-pip** (This will be needed to install "tabulate" and "terminaltables")
sudo apt-get install python-pip
**tabulate**
sudo pip install tabulate
**terminaltables**
sudo pip install terminaltables

If any installation failed with "apt-get install command" trying installing with "pip install"

**Install xerosploit**
git clone https://github.com/LionSec/xerosploit
**cd into xerosploit folder**
sudo python install.py


**In case of WARNING while running install.py such as:**
**WARNING**:  bin/xettercap is not executable
**WARNING**:  See http://guides.rubygems.org/specification-reference/ for help

**cd into xerosploit folder**
cd xerosploit/tools/bettercap/bin/
or open ternimal at /xerosploit/tools/bettercap/bin/
**run** sudo chmod +x xettercap


Launch xerosploit
sudo xerosploit

If you have install xerosploit before the dependencies and you still see issue , I recommend you run the xerosploit installer again.
