### ISSUE TITLE
I have a different problem on installing xerosploit

### ISSUE THREAD

**Issue by Robin-Rodrigo** [LionSec/xerosploit#222]
When i type "python install.py" this error comes up

python install.py
 
┌══════════════════════════════════════════════════════════════┐
█                                                              █
█                     Xerosploit Installer                     █
█                                                              █
└══════════════════════════════════════════════════════════════┘     

[++] Please choose your operating system.

1) Ubuntu / Kali linux / Others
2) Parrot OS

>>> 1

[++] Installing Xerosploit ... 
Hit:1 http://kali.cs.nctu.edu.tw/kali kali-rolling InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version (1:2.28.0-1).
hping3 is already the newest version (3.a2.ds2-9).
nmap is already the newest version (7.80+dfsg1-5kali1).
python-pip is already the newest version (20.0.2-5kali1).
python-pip set to manually installed.
ruby-dev is already the newest version (1:2.7+1).
ruby-dev set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgcc1 : Depends: gcc-9-base (= 9.2.1-1) but 9.3.0-15 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
WARNING:  bin/xettercap is not executable
WARNING:  See https://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: xettercap
  Version: 1.5.7xerob
  File: xettercap-1.5.7xerob.gem
Building native extensions. This could take a while...
ERROR:  Error installing xettercap-1.5.7xerob.gem:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.7.0/gems/eventmachine-1.2.7/ext
/usr/bin/ruby2.7 -I /usr/local/lib/site_ruby/2.7.0 -r ./siteconf20200820-2539-12ike4q.rb extconf.rb
checking for -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.7
	--with-ssl-dir
	--without-ssl-dir
	--with-ssl-include
	--without-ssl-include=${ssl-dir}/include
	--with-ssl-lib
	--without-ssl-lib=${ssl-dir}/lib
	--with-openssl-config
	--without-openssl-config
	--with-pkg-config
	--without-pkg-config
	--with-crypto-dir
	--without-crypto-dir
	--with-crypto-include
	--without-crypto-include=${crypto-dir}/include
	--with-crypto-lib
	--without-crypto-lib=${crypto-dir}/lib
	--with-cryptolib
	--without-cryptolib
/usr/lib/ruby/2.7.0/mkmf.rb:471:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/lib/ruby/2.7.0/mkmf.rb:564:in `try_link0'
	from /usr/lib/ruby/2.7.0/mkmf.rb:582:in `try_link'
	from /usr/lib/ruby/2.7.0/mkmf.rb:801:in `try_func'
	from /usr/lib/ruby/2.7.0/mkmf.rb:1029:in `block in have_library'
	from /usr/lib/ruby/2.7.0/mkmf.rb:971:in `block in checking_for'
	from /usr/lib/ruby/2.7.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /usr/lib/ruby/2.7.0/mkmf.rb:331:in `open'
	from /usr/lib/ruby/2.7.0/mkmf.rb:361:in `block in postpone'
	from /usr/lib/ruby/2.7.0/mkmf.rb:331:in `open'
	from /usr/lib/ruby/2.7.0/mkmf.rb:357:in `postpone'
	from /usr/lib/ruby/2.7.0/mkmf.rb:970:in `checking_for'
	from /usr/lib/ruby/2.7.0/mkmf.rb:1024:in `have_library'
	from extconf.rb:8:in `block in check_libs'
	from extconf.rb:8:in `all?'
	from extconf.rb:8:in `check_libs'
	from extconf.rb:95:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.7.0/extensions/x86_64-linux/2.7.0/eventmachine-1.2.7/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.7.0/gems/eventmachine-1.2.7 for inspection.
Results logged to /var/lib/gems/2.7.0/extensions/x86_64-linux/2.7.0/eventmachine-1.2.7/gem_make.out
Xerosploit has been sucessfuly instaled. Execute 'xerosploit' in your terminal.

then i type xerosploit . It gives me this error

bash: xerosploit: command not found

btw I'm running latest version of kali linux -2020.3

If u know how to solve this problem. plzzzzzzzzzzzzzzzzz  help meeee

**Comment by The4n0n** [comment]
> When i type "python install.py" this error comes up
> 
> python install.py
> 
> ┌══════════════════════════════════════════════════════════════┐
> █ █
> █ Xerosploit Installer █
> █ █
> └══════════════════════════════════════════════════════════════┘
> 
> [++] Please choose your operating system.
> 
> 1. Ubuntu / Kali linux / Others
> 2. Parrot OS
> 
> > > > 1
> 
> [++] Installing Xerosploit ...
> Hit:1 http://kali.cs.nctu.edu.tw/kali kali-rolling InRelease
> Reading package lists... Done
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> git is already the newest version (1:2.28.0-1).
> hping3 is already the newest version (3.a2.ds2-9).
> nmap is already the newest version (7.80+dfsg1-5kali1).
> python-pip is already the newest version (20.0.2-5kali1).
> python-pip set to manually installed.
> ruby-dev is already the newest version (1:2.7+1).
> ruby-dev set to manually installed.
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
> libgcc1 : Depends: gcc-9-base (= 9.2.1-1) but 9.3.0-15 is to be installed
> E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
> WARNING: bin/xettercap is not executable
> WARNING: See https://guides.rubygems.org/specification-reference/ for help
> Successfully built RubyGem
> Name: xettercap
> Version: 1.5.7xerob
> File: xettercap-1.5.7xerob.gem
> Building native extensions. This could take a while...
> ERROR: Error installing xettercap-1.5.7xerob.gem:
> ERROR: Failed to build gem native extension.
> 
> ```
> current directory: /var/lib/gems/2.7.0/gems/eventmachine-1.2.7/ext
> ```
> 
> /usr/bin/ruby2.7 -I /usr/local/lib/site_ruby/2.7.0 -r ./siteconf20200820-2539-12ike4q.rb extconf.rb
> checking for -lcrypto... *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers. Check the mkmf.log file for more details. You may
> need configuration options.
> 
> Provided configuration options:
> --with-opt-dir
> --without-opt-dir
> --with-opt-include
> --without-opt-include=${opt-dir}/include
> --with-opt-lib
> --without-opt-lib=${opt-dir}/lib
> --with-make-prog
> --without-make-prog
> --srcdir=.
> --curdir
> --ruby=/usr/bin/$(RUBY_BASE_NAME)2.7
> --with-ssl-dir
> --without-ssl-dir
> --with-ssl-include
> --without-ssl-include=${ssl-dir}/include
> --with-ssl-lib
> --without-ssl-lib=${ssl-dir}/lib
> --with-openssl-config
> --without-openssl-config
> --with-pkg-config
> --without-pkg-config
> --with-crypto-dir
> --without-crypto-dir
> --with-crypto-include
> --without-crypto-include=${crypto-dir}/include
> --with-crypto-lib
> --without-crypto-lib=${crypto-dir}/lib
> --with-cryptolib
> --without-cryptolib
> /usr/lib/ruby/2.7.0/mkmf.rb:471:in `try_do': The compiler failed to generate an executable file. (RuntimeError) You have to install development tools first. from /usr/lib/ruby/2.7.0/mkmf.rb:564:in `try_link0'
> from /usr/lib/ruby/2.7.0/mkmf.rb:582:in `try_link' from /usr/lib/ruby/2.7.0/mkmf.rb:801:in `try_func'
> from /usr/lib/ruby/2.7.0/mkmf.rb:1029:in `block in have_library' from /usr/lib/ruby/2.7.0/mkmf.rb:971:in `block in checking_for'
> from /usr/lib/ruby/2.7.0/mkmf.rb:361:in `block (2 levels) in postpone' from /usr/lib/ruby/2.7.0/mkmf.rb:331:in `open'
> from /usr/lib/ruby/2.7.0/mkmf.rb:361:in `block in postpone' from /usr/lib/ruby/2.7.0/mkmf.rb:331:in `open'
> from /usr/lib/ruby/2.7.0/mkmf.rb:357:in `postpone' from /usr/lib/ruby/2.7.0/mkmf.rb:970:in `checking_for'
> from /usr/lib/ruby/2.7.0/mkmf.rb:1024:in `have_library' from extconf.rb:8:in `block in check_libs'
> from extconf.rb:8:in `all?' from extconf.rb:8:in `check_libs'
> from extconf.rb:95:in `
> 
> '
> To see why this extension failed to compile, please check the mkmf.log which can be found here:
> 
> /var/lib/gems/2.7.0/extensions/x86_64-linux/2.7.0/eventmachine-1.2.7/mkmf.log
> 
> extconf failed, exit code 1
> 
> Gem files will remain installed in /var/lib/gems/2.7.0/gems/eventmachine-1.2.7 for inspection.
> Results logged to /var/lib/gems/2.7.0/extensions/x86_64-linux/2.7.0/eventmachine-1.2.7/gem_make.out
> Xerosploit has been sucessfuly instaled. Execute 'xerosploit' in your terminal.
> 
> then i type xerosploit . It gives me this error
> 
> bash: xerosploit: command not found
> 
> btw I'm running latest version of kali linux -2020.3
> 
> If u know how to solve this problem. plzzzzzzzzzzzzzzzzz help meeee

1. apt install -f
2. apt autoremove

1.
