### ISSUE TITLE
Not Run Xerosploit

### ISSUE THREAD

**Issue by ermelonyxd** [LionSec/xerosploit#239]
python3
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/opt/xerosploit/xerosploit.py", line 866, in cmd0
    cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip()
NameError: name 'raw_input' is not defined
 

and python2

Traceback (most recent call last):
  File "xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables
                                            
install tabulate and terminaltables but for python3

**Comment by fedetrifo06** [comment]
same error

**Comment by nickluong-dev** [comment]
I followed this video to fix the error: https://www.youtube.com/watch?v=CxYuLYpdDEA.
