### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by tvrezanemati** [LionSec/xerosploit#240]
python3 xerosploit.py
Traceback (most recent call last):
  File "xerosploit.py", line 980, in main
    home()
  File "xerosploit.py", line 62, in home
    config0()
  File "xerosploit.py", line 44, in config0
    up_interface = open('/opt/xerosploit/tools/files/iface.txt', 'r').read()
FileNotFoundError: [Errno 2] No such file or directory: '/opt/xerosploit/tools/files/iface.txt'

**Comment by techvineyy** [comment]
Xerosploit is built over python2 so it can't be run using python3, please try:
`sudo python2 ./xerosploit.py`
or
`sudo python ./xerosploit.py`
It may work.

**Comment by deep1ne9** [comment]
Just install the python futurize package - **apt install python3-future**
[Futurize: py2 to py3 conversion link](https://python-future.org/futurize.html)
Then run the below command against your python2 code inside the directory:
_**python3-futurize -a -0 -w -v /python2-dir/*.py**_
you can now execute code using **_python3 "your-python2-code.py"_**
