### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by santoshdawre** [LionSec/xerosploit#243]
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/opt/xerosploit/xerosploit.py", line 866, in cmd0
    cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip()
NameError: name 'raw_input' is not defined

That the error i got

_Originally posted by @Ralphacan in https://github.com/LionSec/xerosploit/issues/77#issuecomment-555948979_

**Comment by ifexx** [comment]
Same

**Comment by poiper** [comment]
all you have to do is change **raw_input()** to **input()**

reason: **_raw_input() is just defined as a variable and is not defined, vs input() is function to take user input through the terminal._** 

btw here the **[dropbox](https://www.dropbox.com/sh/hvvs1lc4vy3t8p9/AAC8s9NQsCnZuLvqdC0xpqKOa?dl=0l)**
╔══════════════════════════════╗
║ -**MAKE SURE YOU INSTALL THE REQUIRED DEPENDENCIES** -║
╚══════════════════════════════╝
