### ISSUE TITLE
# python3 xerosploit.py     

### ISSUE THREAD

**Issue by ifexx** [LionSec/xerosploit#244]
Traceback (most recent call last):
  File "/home/eye/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/home/eye/xerosploit/xerosploit.py", line 866, in cmd0
    cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip()
NameError: name 'raw_input' is not defined

**Comment by ifexx** [comment]
/usr/bin/pip3 install tabulate                                                                   
Traceback (most recent call last):
  File "/usr/bin/pip3", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources.py", line 1479, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

**Comment by ifexx** [comment]
└─# /usr/bin/pip3 install terminaltable                                                              
Traceback (most recent call last):
  File "/usr/bin/pip3", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources.py", line 1479, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

**Comment by aNDOhACK** [comment]
i have same  problem
Traceback (most recent call last):
  File "/home/aliyos/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/home/aliyos/xerosploit/xerosploit.py", line 866, in cmd0
    cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip()
NameError: name 'raw_input' is not defined

**Comment by Radiance37k** [comment]
I haven't done any extensive testing on this, but it seems to work:
Replace any occurrence of `raw_input` with `input`.
You might also need to change the shebang from `#!/usr/bin/python` to `#!/usr/bin/python3`

raw_input seems to be deprecated in python3

**Comment by nickluong-dev** [comment]
install 2to3 and convert xerosploit.py. 

Here is a video for reference.

**Comment by irhdab** [comment]
try running with python2.7
