### ISSUE TITLE
issue when running replace

### ISSUE THREAD

**Issue by Prograb** [LionSec/xerosploit#250]
when i run the replace command i get this error:

Traceback (most recent call last):
  File "/home/kali/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/home/kali/xerosploit/xerosploit.py", line 871, in cmd0
    target_ip()
  File "/home/kali/xerosploit/xerosploit.py", line 855, in target_ip
    program0()
  File "/home/kali/xerosploit/xerosploit.py", line 829, in program0
    option()
  File "/home/kali/xerosploit/xerosploit.py", line 825, in option
    option()
  File "/home/kali/xerosploit/xerosploit.py", line 694, in option
    shakescreen()
  File "/home/kali/xerosploit/xerosploit.py", line 689, in shakescreen
    shakescreen()
  File "/home/kali/xerosploit/xerosploit.py", line 680, in shakescreen
    option()
  File "/home/kali/xerosploit/xerosploit.py", line 825, in option
    option()
  File "/home/kali/xerosploit/xerosploit.py", line 635, in option
    replace()
  File "/home/kali/xerosploit/xerosploit.py", line 612, in replace
    img_replace = eval(input("\033[1;36m\033[4mXero\033[0m»\033[1;36m\033[4mmodules\033[0m»\033[1;36m\033[4mreplace\033[0m\033[1;36m ➮ \033[1;m"))
  File "<string>", line 1
    /home/kali/ayWKreNC.jpg
    ^
SyntaxError: invalid syntax

oh and btw, other commands dont work aswell, only move seems to work

**Comment by Prograb** [comment]
help?

**Comment by Prograb** [comment]
help..?

**Comment by Prograb** [comment]
brh

**Comment by Prograb** [comment]
bruh

**Comment by Prograb** [comment]
bruh come on, if it's a dumb question just tell me

**Comment by Prograb** [comment]
bruh

**Comment by Prograb** [comment]
I quit.
