### ISSUE TITLE
Unable to install on Parrot OS

### ISSUE THREAD

**Issue by NoNameInspectah** [LionSec/xerosploit#252]
Hi.. I just git cloned into the file and when i attempted to do sudo python install.py it proceeded to show me 

"Traceback (most recent call last):
  File "/home/inspectah/Downloads/xerosploit-master/install.py", line 65, in <module>
    main()
  File "/home/inspectah/Downloads/xerosploit-master/install.py", line 45, in main
    system0 = raw_input(">>> ")
NameError: name 'raw_input' is not defined
"

Any way to fix this please let me know.

**Comment by Trgreene08** [comment]
I'm also having this problem. except mine says
```

 [++] Please choose your operating system.

1) Ubuntu / Kali linux / Others
2) Parrot OS

Traceback (most recent call last):
  File "/home/atom/src/xerosploit/install.py", line 65, in <module>
    main()
  File "/home/atom/src/xerosploit/install.py", line 45, in main
    system0 = raw_input(">>> ")
NameError: name 'raw_input' is not defined
```

Seems like it should be simple enough to fix. I've only been working with linux for the past 6 months and I don't know what the correct syntax would be to define the variable. It looks as though its supposed to ask you which distros your using, Kali/Ubuntu or Parrot and you enter 1 or 2 for your OS and it follows that defined set of operations to conitnue the installation. 

I went into text editor and tried to define line 45 briefly with no luck
`system0 = raw_input(">>> ")`
I treid 
```
system0 = raw_input(">>>2")
system0 = raw_input("2")
system0 = raw_input(2)
system0 = raw_input 2
```

and most variations of that that occured to me at the moment. Logically this is simple af

I'll do a bit of research and report back a solution

**Comment by Anonymous2309** [comment]
Just change the raw_input to input

**Comment by Iyaad-luqman** [comment]
replace every raw_input to input 
raw_input is python2 command for input of python3

**Comment by NoNameInspectah** [comment]
Okay so i did what @Iyaad-luqman suggested and changed everything to "input" but when i ran "sudo xerosploit" it showed me the logo and my ip configs but than showed me 

`╔═════════════╦════════════════════════════════════════════════════════════════════╗
║             ║ XeroSploit is a penetration testing toolkit whose goal is to       ║
║ Information ║ perform man in the middle attacks for testing purposes.            ║
║             ║ It brings various modules that allow to realise efficient attacks. ║
║             ║ This tool is Powered by Bettercap and Nmap.                        ║
╚═════════════╩════════════════════════════════════════════════════════════════════╝

[+] Please type 'help' to view commands.

Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/opt/xerosploit/xerosploit.py", line 866, in cmd0
    cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip()
NameError: name 'raw_input' is not defined
┌─[inspectah@parrot]─[~/xerosploit]
└──╼ $
`

I don't know what to do with this at the current moment.. In needs of help.

**Comment by Iyaad-luqman** [comment]
Maybe you did'nt replace it properly . just  download this file and replace it in your cloned xerosploit directory:
https://drive.google.com/file/d/1jlfz3YenL27cafFt2vJYqhcA7V624mzk/view?usp=sharing

**Comment by Anonymous2309** [comment]
Just replace every raw input with input or run it with python2

**Comment by Trgreene08** [comment]
> Just change the raw_input to input

this fixed the problem for me. thanks guys
