### ISSUE TITLE
how do i fix this? thanks 

### ISSUE THREAD

**Issue by Curtis2504** [LionSec/xerosploit#259]
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 980, in main
    home()
  File "/opt/xerosploit/xerosploit.py", line 62, in home
    config0()
  File "/opt/xerosploit/xerosploit.py", line 44, in config0
    up_interface = open('./tools/files/iface.txt', 'r').read()
IOError: [Errno 2] No such file or directory: './tools/files/iface.txt'

**Comment by Rukksan14** [comment]
sane
Traceback (most recent call last):
  File "/home/Rukksan14/xerosploit/xerosploit.py", line 980, in main
    home()
  File "/home/Rukksan14/xerosploit/xerosploit.py", line 62, in home
    config0()
  File "/home/Rukksan14/xerosploit/xerosploit.py", line 44, in config0
    up_interface = open('/opt/xerosploit/tools/files/iface.txt', 'r').read()
FileNotFoundError: [Errno 2] No such file or directory: '/opt/xerosploit/tools/files/iface.txt'

**Comment by Travon112200** [comment]
Guys as you can see this tools was published 5 years ago and it was built under python 2 now everything has changed and the tool is not even updated

**Comment by hack-im** [comment]
Hey Guys, I fixed the problem ;
- download this : https://www.mediafire.com/file/rgtsnu9zshzqur4/xerosploit.tar.gz/file
- then dezip
- Tap : python3 xerosploit.py 

Ask me your question 👍

that was Nemesis (Targaryen) s/o Daenerys s/o Egon
