### ISSUE TITLE
Xerosploit is not working with Python-3. (NameError: name 'raw_input' is not defined)

### ISSUE THREAD

**Issue by BONTEAR** [LionSec/xerosploit#261]
### Issue:
_____________________________________________________________________________________________   
Traceback (most recent call last):                                                                                         
  File "/home/bontear/Desktop/all/xerosploit/xerosploit2.py", line 981, in main                 
    cmd0()
  File "/home/bontear/Desktop/all/xerosploit/xerosploit2.py", line 866, in cmd0                    
    cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip()      
NameError: name 'raw_input' is not defined
_____________________________________________________________________________________________

### Follow the steps to fix it:

**Step-1:**
> "**sudo nano xerosploit.py**"
Then Press "**Ctrl+\**" on your keyboard and type "**raw_input**" and press enter.
After that type "**input**" and press enter, it will ask to replace all press "**A**" and enter.
After doing all those, Press "**Ctrl+o**" to save and then "**Ctrl+x**" to exit.

The problem should get fixed, run it to check.
> "**sudo python3 xerosploit.py**"

**Stem-2:**
If that didn't work, manually open the file with a text editor and replace all the "**raw_input**" with "**input**" and save it.

**Comment by dsxz19-2** [comment]
Ya same i got "raw_input not defined" error but i fixed it

in the "install.py" file in line 48 or where ever it says:

install = os.system("apt-get update && apt-get install -y nmap hping3 build-essential python-pip ruby-dev git libpcap-dev libgmp3-dev && pip install tabulate terminaltables")

replace python-pip with python3-pip

at the top were you import modules add this "from six.moves import input" without the " "

copy and past the xerosploit.py code into a google docs or somewhere where you can do a mass replace

if you are using google docs press ctrl+h and in the first line type raw_input and in the second line type input

and then click "replace all"

I hope this helps. :)

**Comment by chrismuntean** [comment]
> ### Issues:
> 
> Traceback (most recent call last): File "/home/bontear/Desktop/all/xerosploit/xerosploit.py", line 981, in main cmd0() File "/home/bontear/Desktop/all/xerosploit/xerosploit.py", line 866, in cmd0 cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip() NameError: name 'raw_input' is not defined
> 
> And
> 
> Traceback (most recent call last): File "xerosploit.py", line 26, in from terminaltables import DoubleTable ImportError: No module named terminaltables
> ### Follow the steps to fix those issues:
> 
> **Step-1:**
> 
> > "**sudo nano xerosploit.py**"
> 
> Then Press "Ctrl+(Backslash Symbol)" on your keyboard and type "**raw_input**" and press enter. After that type "**input**" and press enter, it will ask to replace all press "**A**" and enter. After doing all those, Press "Ctrl+o" to save and then "Ctrl+x" to exit.
> 
> The problem should get fixed, run it to check.
> 
> > "**sudo python3 xerosploit.py**"
> 
> **Stem-2:** If that didn't work, manually open the file with a text editor and replace all the "**raw_input**" with "**input**" and save it.

do this to both the xerosploit.py AND install.py files and then it worked for me
