### ISSUE TITLE
Xerosploit Commands not Working | Kali 2021.2

### ISSUE THREAD

**Issue by HaroonRehman** [LionSec/xerosploit#268]
[+] Please type 'help' to view commands.

Xero ➮ scan   
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/opt/xerosploit/xerosploit.py", line 866, in cmd0
    cmd_0 = input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip()
AttributeError: 'function' object has no attribute 'strip'

**Comment by leiwuhen92** [comment]
猜测你可能使用python3安装，需要修改执行文件/usr/bin/xerosploit（which xerosploit查看）中的python为python3；
或者直接在项目目录下运行python3 xerosploit.py

**Comment by HaroonRehman** [comment]
Thanks Leiwuhen92
