### ISSUE TITLE
Can't install in Kali Rolling

### ISSUE THREAD

**Issue by d4rkn0** [LionSec/xerosploit#28]
Hi,
i tried to install xerosploit on kali rolling but i got this error message:

> root@unkown:/home/d4rkn0/Downloads/xerosploit# python install.py 
>  
> ┌══════════════════════════════════════════════════════════════┐
> █                                                              █
> █                     Xerosploit Installer                     █
> █                                                              █
> └══════════════════════════════════════════════════════════════┘     
> 
> [++] Please choose your operating system.
> 
> 1) Ubuntu / Kali linux / Others
> 2) Parrot OS
> 
> >>> 1
> 
> [++] Installing Xerosploit ... 
> Hit:1 http://ftp.free.fr/pub/kali kali-rolling InRelease
> Reading package lists... Done
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> build-essential is already the newest version (12.2).
> git is already the newest version (1:2.9.3-1).
> hping3 is already the newest version (3.a2.ds2-7).
> libgmp3-dev is already the newest version (2:6.1.1+dfsg-1).
> libpcap-dev is already the newest version (1.7.4-3).
> nmap is already the newest version (7.30-0kali1).
> python-pip is already the newest version (8.1.2-2).
> ruby-dev is already the newest version (1:2.3.0+4).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Requirement already satisfied (use --upgrade to upgrade): tabulate in /usr/local/lib/python2.7/dist-packages
> Requirement already satisfied (use --upgrade to upgrade): terminaltables in /usr/local/lib/python2.7/dist-packages
> WARNING:  bin/xettercap is not executable
> WARNING:  See http://guides.rubygems.org/specification-reference/ for help
>   Successfully built RubyGem
>   Name: xettercap
>   Version: 1.5.7xerob
>   File: xettercap-1.5.7xerob.gem
> ERROR:  While executing gem ... (TypeError)
>     no implicit conversion of nil into String
> Xerosploit has been sucessfuly instaled. Execute 'xerosploit' in your terminal.
> root@unkown:/home/d4rkn0/Downloads/xerosploit# 

i got that Xerosploit has been sucessfuly instaled but if i try to execute 'xerosploit' in terminal i got nothing even if i tried to run xerosploit.py i got this :

> root@unkown:/home/d4rkn0/Downloads/xerosploit# ./xerosploit.py 
> Traceback (most recent call last):
>   File "./xerosploit.py", line 980, in main
>     home()
>   File "./xerosploit.py", line 62, in home
>     config0()
>   File "./xerosploit.py", line 44, in config0
>     up_interface = open('/opt/xerosploit/tools/files/iface.txt', 'r').read()
> IOError: [Errno 2] No such file or directory: '/opt/xerosploit/tools/files/iface.txt'
> root@unkown:/home/d4rkn0/Downloads/xerosploit#

**Comment by zhaoxiaobu** [comment]
Hi, i have the same problem,how to fix it?

**Comment by Mehdiranian** [comment]
move xerosploit folder to /opt directory
or 
such: move xerosploit folder to /root directory 
and
open xerosploit.py and change all address 
/opt/xerosploit/...     to    /root/xerosploit/...

**Comment by script-planet** [comment]
Help me 

Traceback (most recent call last):
  File "xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables
