### ISSUE TITLE
kali 安装依赖包时出现,求解决办法

### ISSUE THREAD

**Issue by lijia0928** [LionSec/xerosploit#293]
Traceback (most recent call last):
  File "/root/xerosploit/install.py", line 65, in <module>
    main()
  File "/root/xerosploit/install.py", line 45, in main
    system0 = raw_input(">>> ")
NameError: name 'raw_input' is not defined

**Comment by lijia0928** [comment]
找到了解决办法，出现这种情况说明使用的python3安装的。
输入命令：cd xerosploit && sudo python2 install.py
就可以了。

**Comment by AvinFajarF** [comment]
> Traceback (most recent call last): File "/root/xerosploit/install.py", line 65, in main() File "/root/xerosploit/install.py", line 45, in main system0 = raw_input(">>> ") NameError: name 'raw_input' is not defined

Please replace all the "raw_input" with only "input". This will resolve the issue. The updated python uses this new syntax and the keyword "raw_input" has been replaced by "input"
