### ISSUE TITLE
NameError: name 'raw_input' is not defined

### ISSUE THREAD

**Issue by pawscanthack** [LionSec/xerosploit#297]
Doesn't install on updated Kali Linux: 
Traceback (most recent call last):
  File "/root/xerosploit/install.py", line 65, in <module>
    main()
  File "/root/xerosploit/install.py", line 45, in main
    system0 = raw_input(">>> ")
NameError: name 'raw_input' is not defined

**Comment by yoitsankey** [comment]
Step1 . Open install.py and xerosploit.py respectively in a text editor.
Step 2. Then Go to Find and Replace.
Step 3. Now, Enter "raw_input" in Find section of find and replace tool (without quotations ).
Step 4. and then Enter "input" in Replace section of find and replace tool (without quotations).
Step 5. Now replace all the occurences with above value.
Step 6. save the file and exit.
Step 7. Now run the install.py with python3 install it.
Step 8. after installation run xerosploit.py with python3 in order to get it working.
Step 9. (optional)
If you want to directly run xerosploit from the terminal instead of using python3 everytime with xerosploit.py, Go to /opt/xersploit, and now find and replace all the occurences of raw_input with input as explained above.

BOOM!!! Congratulations You get it working

**Comment by pawscanthack** [comment]
I will try this, thanks for your assistance😎
________________________________

**Comment by yoitsankey** [comment]
Inform me when you will get it working..
Happy to help Mate!!

**Comment by XM1N21KR1** [comment]
> Step1 . Open install.py and xerosploit.py respectively in a text editor. Step 2. Then Go to Find and Replace. Step 3. Now, Enter "raw_input" in Find section of find and replace tool (without quotations ). Step 4. and then Enter "input" in Replace section of find and replace tool (without quotations). Step 5. Now replace all the occurences with above value. Step 6. save the file and exit. Step 7. Now run the install.py with python3 install it. Step 8. after installation run xerosploit.py with python3 in order to get it working. Step 9. (optional) If you want to directly run xerosploit from the terminal instead of using python3 everytime with xerosploit.py, Go to /opt/xersploit, and now find and replace all the occurences of raw_input with input as explained above.
> 
> BOOM!!! Congratulations You get it working

Working! Thankyou hero

**Comment by kishwordulal** [comment]
> 

please can you help me in fixing this error 
i am geting error time to time

**Comment by yoitsankey** [comment]
Just follow the steps mentioned above.
