### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by kyujin100715** [LionSec/xerosploit#307]
Traceback (most recent call last):
  File "/home/rooot/xerosploit/install.py", line 65, in <module>
    main()
  File "/home/rooot/xerosploit/install.py", line 45, in main
    system0 = raw_input(">>> ")
NameError: name 'raw_input' is not defined

**Comment by OreoSalada** [comment]
open install.py with nano, then change the line 45 "system0 = raw_input..." to "system0 = input..."
