### ISSUE TITLE
Pyhon3 install.py error

### ISSUE THREAD

**Issue by AvinFajarF** [LionSec/xerosploit#317]
Traceback (most recent call last):
  File "/home/roboti0i5/tools/xerosploit/install.py", line 65, in <module>
    main()
  File "/home/roboti0i5/tools/xerosploit/install.py", line 45, in main
    system0 = raw_input(">>> ")
NameError: name 'raw_input' is not defined

how do i fix it?

**Comment by Guidenevada** [comment]
type in terminal : sudo python2 install.py

**Comment by AvinFajarF** [comment]
> ketik terminal: sudo python2 install.py

it didn't work bro

**Comment by AvinFajarF** [comment]
Nothing
