### ISSUE TITLE
/var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/bin/xettercap:51:in `rescue in <top (required)>

### ISSUE THREAD

**Issue by XM1N21KR1** [LionSec/xerosploit#319]
Does anybody here know how to fix this? 

/var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/bin/xettercap:51:in `rescue in <top (required)>': undefined local variable or method `original_argv' for main:Object (NameError)
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/bin/xettercap:32:in `<top (required)>'
        from /usr/local/bin/xettercap:25:in `load'
        from /usr/local/bin/xettercap:25:in `<main>'
/usr/lib/ruby/3.0.0/set/sorted_set.rb:4:in `rescue in <top (required)>': The `SortedSet` class has been extracted from the `set` library.You must use the `sorted_set` gem or other alternatives. (RuntimeError)
        from /usr/lib/ruby/3.0.0/set/sorted_set.rb:1:in `<top (required)>'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:93:in `const_get'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:93:in `block in each_module'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:92:in `each'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:92:in `each_module'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:71:in `register_options'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:53:in `load'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/options/proxy_options.rb:164:in `block in parse!'
        from /usr/lib/ruby/3.0.0/optparse.rb:1618:in `block in parse_in_order'
        from /usr/lib/ruby/3.0.0/optparse.rb:1601:in `catch'
        from /usr/lib/ruby/3.0.0/optparse.rb:1601:in `parse_in_order'
        from /usr/lib/ruby/3.0.0/optparse.rb:1595:in `order!'
        from /usr/lib/ruby/3.0.0/optparse.rb:1701:in `permute!'
        from /usr/lib/ruby/3.0.0/optparse.rb:1726:in `parse!'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/options/options.rb:54:in `parse!'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/bin/xettercap:24:in `<top (required)>'
        from /usr/local/bin/xettercap:25:in `load'
        from /usr/local/bin/xettercap:25:in `<main>'
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- sorted_set (LoadError)
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/lib/ruby/3.0.0/set/sorted_set.rb:2:in `<top (required)>'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:93:in `const_get'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:93:in `block in each_module'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:92:in `each'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:92:in `each_module'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:71:in `register_options'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:53:in `load'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/options/proxy_options.rb:164:in `block in parse!'
        from /usr/lib/ruby/3.0.0/optparse.rb:1618:in `block in parse_in_order'
        from /usr/lib/ruby/3.0.0/optparse.rb:1601:in `catch'
        from /usr/lib/ruby/3.0.0/optparse.rb:1601:in `parse_in_order'
        from /usr/lib/ruby/3.0.0/optparse.rb:1595:in `order!'
        from /usr/lib/ruby/3.0.0/optparse.rb:1701:in `permute!'
        from /usr/lib/ruby/3.0.0/optparse.rb:1726:in `parse!'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/options/options.rb:54:in `parse!'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/bin/xettercap:24:in `<top (required)>'
        from /usr/local/bin/xettercap:25:in `load'
        from /usr/local/bin/xettercap:25:in `<main>'

[+] Enter 'run' to execute the 'replace' command.

**Comment by omerfdmrl** [comment]
any update?

**Comment by XM1N21KR1** [comment]
> any update?

nope, still have the same issue

**Comment by shadhack** [comment]
> > any update?
> 
> nope, still have the same issue

did you fix it ?

**Comment by apambalik1337** [comment]
> sudo gem install sorted_set

IT WORKING BROOO THANKYOU SO MUCH

**Comment by apambalik1337** [comment]
> > > any update?
> > 
> > 
> > nope, still have the same issue
> 
> did you fix it ?
> 
> if you didnt try this
> 
> sudo gem install sorted_set

injecthtml is working but went I try to deface all webpage with my HTML code I got this

[+] Enter 'run' to execute the 'deface' command.                                                                                                    
                                                                                                                                                    
Xero»modules»deface ➮ run

[+] Specify the file containing your defacement code .                                                                                              

[!] Your file should not contain Javascript code .                                                                                                  
                                                                                                                                                    
Xero»modules»deface ➮ /home/x/AOXdeface/violet.html

[++] Overwriting all web pages ...                                                                                                                  

[++] Press 'Ctrl + C' to stop .                                                                                                                     
                                                                                                                                                    
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/opt/xerosploit/xerosploit.py", line 869, in cmd0
    scan()
  File "/opt/xerosploit/xerosploit.py", line 129, in scan
    target_ip()
  File "/opt/xerosploit/xerosploit.py", line 855, in target_ip
    program0()
  File "/opt/xerosploit/xerosploit.py", line 829, in program0
    option()
  File "/opt/xerosploit/xerosploit.py", line 825, in option
    option()
  File "/opt/xerosploit/xerosploit.py", line 359, in option
    inject_html()
  File "/opt/xerosploit/xerosploit.py", line 354, in inject_html
    inject_html()
  File "/opt/xerosploit/xerosploit.py", line 333, in inject_html
    option()
  File "/opt/xerosploit/xerosploit.py", line 825, in option
    option()
  File "/opt/xerosploit/xerosploit.py", line 784, in option
    deface()
  File "/opt/xerosploit/xerosploit.py", line 774, in deface
    f1 = open('/home/home/xero-html.html','w')
FileNotFoundError: [Errno 2] No such file or directory: '/home/home/xero-html.html'

**Comment by XM1N21KR1** [comment]
> sudo gem install sorted_set

run sudo gem install sorted_set

**Comment by apambalik1337** [comment]
> any update?

run this maybe it can fix the issue

sudo gem install sorted_set

**Comment by andrepg-dev** [comment]
> > sudo joya instalar sorted_set
> 
> FUNCIONA BROOO MUCHAS GRACIAS

Pudiste solucionar? Tengo exactamente el mismo error, escribí "sudo gem install sorted_se" y se puso también como el tuyo alv

**Comment by marcustyler-08** [comment]
still not working for me

AFTER RUNNING `sudo gem install sorted_set`

output:

``` /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/bin/xettercap:51:in `rescue in <top (required)>': undefined local variable or method `original_argv' for main:Object (NameError)
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/bin/xettercap:32:in `<top (required)>'
        from /usr/local/bin/xettercap:25:in `load'
        from /usr/local/bin/xettercap:25:in `<main>'
/usr/lib/ruby/3.0.0/set/sorted_set.rb:4:in `rescue in <top (required)>': The `SortedSet` class has been extracted from the `set` library.You must use the `sorted_set` gem or other alternatives. (RuntimeError)
        from /usr/lib/ruby/3.0.0/set/sorted_set.rb:1:in `<top (required)>'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:93:in `const_get'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:93:in `block in each_module'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:92:in `each'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:92:in `each_module'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:71:in `register_options'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:53:in `load'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/options/proxy_options.rb:164:in `block in parse!'
        from /usr/lib/ruby/3.0.0/optparse.rb:1618:in `block in parse_in_order'
        from /usr/lib/ruby/3.0.0/optparse.rb:1601:in `catch'
        from /usr/lib/ruby/3.0.0/optparse.rb:1601:in `parse_in_order'
        from /usr/lib/ruby/3.0.0/optparse.rb:1595:in `order!'
        from /usr/lib/ruby/3.0.0/optparse.rb:1701:in `permute!'
        from /usr/lib/ruby/3.0.0/optparse.rb:1726:in `parse!'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/options/options.rb:54:in `parse!'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/bin/xettercap:24:in `<top (required)>'
        from /usr/local/bin/xettercap:25:in `load'
        from /usr/local/bin/xettercap:25:in `<main>'
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- sorted_set (LoadError)
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/lib/ruby/3.0.0/set/sorted_set.rb:2:in `<top (required)>'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:93:in `const_get'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:93:in `block in each_module'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:92:in `each'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:92:in `each_module'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:71:in `register_options'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:53:in `load'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/options/proxy_options.rb:164:in `block in parse!'
        from /usr/lib/ruby/3.0.0/optparse.rb:1618:in `block in parse_in_order'
        from /usr/lib/ruby/3.0.0/optparse.rb:1601:in `catch'
        from /usr/lib/ruby/3.0.0/optparse.rb:1601:in `parse_in_order'
        from /usr/lib/ruby/3.0.0/optparse.rb:1595:in `order!'
        from /usr/lib/ruby/3.0.0/optparse.rb:1701:in `permute!'
        from /usr/lib/ruby/3.0.0/optparse.rb:1726:in `parse!'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/options/options.rb:54:in `parse!'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/bin/xettercap:24:in `<top (required)>'
        from /usr/local/bin/xettercap:25:in `load'
        from /usr/local/bin/xettercap:25:in `<main>' ```

**Comment by 8Lifes** [comment]
After try it : sudo python3 xerosploi.py

Traceback (most recent call last):
  File "/root/xerosploit/xerosploit.py", line 980, in main
    home()
  File "/root/xerosploit/xerosploit.py", line 62, in home
    config0()
  File "/root/xerosploit/xerosploit.py", line 44, in config0
    up_interface = open('/opt/xerosploit/tools/files/iface.txt', 'r').read()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/xerosploit/tools/files/iface.txt'
