### ISSUE TITLE
Unable to sniff post data. Undefined method `unescape' for URI:Module

### ISSUE THREAD

**Issue by Akshay-Arjun** [LionSec/xerosploit#331]
When using the sniff module and if the victom sends post data it is not capturing the data.
```
[W] Could not handle POST request from {I.P} ...
[W] Exception : NoMethodError
Message   : undefined method `unescape' for URI:Module
Backtrace :

    /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/stream_logger.rb:89:in `block in dump_form'
    /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/stream_logger.rb:85:in `each'
    /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/stream_logger.rb:85:in `dump_form'
    /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/stream_logger.rb:141:in `log_post'
    /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/stream_logger.rb:177:in `log_http'
    /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/streamer.rb:71:in `handle'
    /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/proxy.rb:156:in `client_worker'
    /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/proxy.rb:52:in `block in initialize'
    /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/thread_pool.rb:105:in `block in spawn_thread'
```

**Comment by Akshay-Arjun** [comment]
This is because URI.unescape is deprecated. Fixed in #332
