### ISSUE TITLE
Error in running all Modules 

### ISSUE THREAD

**Issue by SaeidJavadi** [LionSec/xerosploit#334]
**When I want to use Modules, I am confronted with this error, does anyone know what the problem is?**

/var/lib/gems/3.1.0/gems/xettercap-1.5.7xerob/bin/xettercap:51:in `rescue in <top (required)>': undefined local variable or method `original_argv' for main:Object (NameError)

  BetterCap::Logger.error "Command Line      : #{original_argv.join(" ")}"
                                                 ^^^^^^^^^^^^^
        from /var/lib/gems/3.1.0/gems/xettercap-1.5.7xerob/bin/xettercap:32:in `<top (required)>'
        from /usr/local/bin/xettercap:25:in `load'
        from /usr/local/bin/xettercap:25:in `<main>'
/usr/lib/ruby/3.1.0/set/sorted_set.rb:4:in `rescue in <top (required)>': The `SortedSet` class has been extracted from the `set` library. You must use the `sorted_set` gem or other alternatives. (RuntimeError)
        from /usr/lib/ruby/3.1.0/set/sorted_set.rb:1:in `<top (required)>'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /var/lib/gems/3.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:93:in `const_get'
        from /var/lib/gems/3.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:93:in `block in each_module'
        from /var/lib/gems/3.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:92:in `each'
        from /var/lib/gems/3.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:92:in `each_module'
        from /var/lib/gems/3.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:71:in `register_options'
        from /var/lib/gems/3.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:53:in `load'
        from /var/lib/gems/3.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/options/proxy_options.rb:164:in `block in parse!'
        from /usr/lib/ruby/3.1.0/optparse.rb:1576:in `block in parse_in_order'
        from /usr/lib/ruby/3.1.0/optparse.rb:1559:in `catch'
        from /usr/lib/ruby/3.1.0/optparse.rb:1559:in `parse_in_order'
        from /usr/lib/ruby/3.1.0/optparse.rb:1553:in `order!'
        from /usr/lib/ruby/3.1.0/optparse.rb:1659:in `permute!'
        from /usr/lib/ruby/3.1.0/optparse.rb:1684:in `parse!'
        from /var/lib/gems/3.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/options/options.rb:54:in `parse!'
        from /var/lib/gems/3.1.0/gems/xettercap-1.5.7xerob/bin/xettercap:24:in `<top (required)>'
        from /usr/local/bin/xettercap:25:in `load'
        from /usr/local/bin/xettercap:25:in `<main>'
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- sorted_set (LoadError)
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/lib/ruby/3.1.0/set/sorted_set.rb:2:in `<top (required)>'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /var/lib/gems/3.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:93:in `const_get'
        from /var/lib/gems/3.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:93:in `block in each_module'
        from /var/lib/gems/3.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:92:in `each'
        from /var/lib/gems/3.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:92:in `each_module'
        from /var/lib/gems/3.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:71:in `register_options'
        from /var/lib/gems/3.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:53:in `load'
        from /var/lib/gems/3.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/options/proxy_options.rb:164:in `block in parse!'
        from /usr/lib/ruby/3.1.0/optparse.rb:1576:in `block in parse_in_order'
        from /usr/lib/ruby/3.1.0/optparse.rb:1559:in `catch'
        from /usr/lib/ruby/3.1.0/optparse.rb:1559:in `parse_in_order'
        from /usr/lib/ruby/3.1.0/optparse.rb:1553:in `order!'
        from /usr/lib/ruby/3.1.0/optparse.rb:1659:in `permute!'
        from /usr/lib/ruby/3.1.0/optparse.rb:1684:in `parse!'
        from /var/lib/gems/3.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/options/options.rb:54:in `parse!'
        from /var/lib/gems/3.1.0/gems/xettercap-1.5.7xerob/bin/xettercap:24:in `<top (required)>'
        from /usr/local/bin/xettercap:25:in `load'
        from /usr/local/bin/xettercap:25:in `<main>'

**OS:** Kali Linux 2022.04
Python3: 3.10.9
python2: 2.7.18

**Comment by tomtzy07** [comment]
any update?
\
