### ISSUE TITLE
Deface and Inject error

### ISSUE THREAD

**Issue by KakaoXI** [LionSec/xerosploit#345]
While i deface tell me this: 
Traceback (most recent call last):
  File "/root/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/root/xerosploit/xerosploit.py", line 869, in cmd0
    scan()
  File "/root/xerosploit/xerosploit.py", line 129, in scan
    target_ip()
  File "/root/xerosploit/xerosploit.py", line 855, in target_ip
    program0()
  File "/root/xerosploit/xerosploit.py", line 829, in program0
    option()
  File "/root/xerosploit/xerosploit.py", line 784, in option
    deface()
  File "/root/xerosploit/xerosploit.py", line 766, in deface
    file_deface  = open(file_deface, 'r').read()
                   ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'root/Scaricati/acqua.html'

While i inject it just say to me press ctrl+c to stop but nothing happens

**Comment by KakaoXI** [comment]
and i can't also install with python, i have to use python3

**Comment by KakaoXI** [comment]
All things i do, inject html, js, images, they say all ctrl+ c to stop but nothing appears and happens
