### ISSUE TITLE
Please help with this!

### ISSUE THREAD

**Issue by mbalomenos** [LionSec/xerosploit#352]
┌─[parrot@parrot]─[~]
└──╼ $cd xerosploit
sudo python3 xerosploit.py
Traceback (most recent call last):
  File "/home/parrot/xerosploit/xerosploit.py", line 980, in main
    home()
  File "/home/parrot/xerosploit/xerosploit.py", line 62, in home
    config0()
  File "/home/parrot/xerosploit/xerosploit.py", line 44, in config0
    up_interface = open('/opt/xerosploit/tools/files/iface.txt', 'r').read()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/xerosploit/tools/files/iface.txt'

**Comment by tubers93os** [comment]
i got the same error.

**Comment by HedgeHogDead** [comment]
sudo apt-get install libpcap-dev

try this

**Comment by HedgeHogDead** [comment]
> i got the same error.

sudo apt-get install libpcap-dev

try this
