### ISSUE TITLE
No such file or directory: '/opt/xerosploit/tools/files/iface.txt'  how to fix it?

### ISSUE THREAD

**Issue by zhaoxiaobu** [LionSec/xerosploit#39]
Hi, i have a problem when i try to use it.
python xerosploit.py 
Traceback (most recent call last):
File "xerosploit.py", line 980, in main
home()
File "xerosploit.py", line 62, in home
config0()
File "xerosploit.py", line 44, in config0
up_interface = open('/opt/xerosploit/tools/files/iface.txt', 'r').read()
IOError: [Errno 2] No such file or directory: '/opt/xerosploit/tools/files/iface.txt'

**Comment by codeunsolved** [comment]
Are you MAC OS X?

**Comment by AibelKingslayer** [comment]
[++] Installing Xerosploit ... 
Hit:1 http://mirrors.neusoft.edu.cn/kali kali-rolling InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.5).
git is already the newest version (1:2.19.0-1).
hping3 is already the newest version (3.a2.ds2-7).
libgmp3-dev is already the newest version (2:6.1.2+dfsg-3).
libpcap-dev is already the newest version (1.8.1-6).
nmap is already the newest version (7.70+dfsg1-3kali1).
python-pip is already the newest version (9.0.1-2.3).
ruby-dev is already the newest version (1:2.5.1).
0 upgraded, 0 newly installed, 0 to remove and 1049 not upgraded.
Requirement already satisfied: tabulate in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: terminaltables in /usr/local/lib/python2.7/dist-packages
WARNING:  bin/xettercap is not executable
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: xettercap
  Version: 1.5.7xerob
  File: xettercap-1.5.7xerob.gem
ERROR:  Could not find a valid gem 'em-proxy' (>= 0.1.8, ~> 0.1), here is why:
          Unable to download data from https://rubygems.org/ - timed out (https://api.rubygems.org/specs.4.8.gz)
Xerosploit has been sucessfuly instaled. Execute 'xerosploit' in your terminal.

Please Please Tell Me How To Fix This
