### ISSUE TITLE
thoughts on this error

### ISSUE THREAD

**Issue by mods6900** [LionSec/xerosploit#4]
root@:~/xerosploit# xerosploit 
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 4, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables

**Comment by LionSec** [comment]
Hello , try to run: 
- pip install terminaltables

**Comment by pavlosidelov** [comment]
I have same issue
pip install terminaltables - Successfully installed terminaltables-3.0.0
---
 sudo xerosploit
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 27, in <module>
    from tabulate import tabulate
ImportError: No module named tabulate
---

What I can do to fix?

**Comment by shajahanak** [comment]
# pip install terminaltables
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 23, in <module>
    from requests.adapters import BaseAdapter
ImportError: No module named adapters
how to fix this issue?

**Comment by matelogic** [comment]
Hello pavlosidelov.

> sudo xerosploit
> Traceback (most recent call last):
> File "/opt/xerosploit/xerosploit.py", line 27, in
> from **tabulate** import **tabulate**

**try to run:
    pip install tabulate**

**Comment by shajahanak** [comment]
~/xerosploit# pip install tabulate
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 23, in <module>
    from requests.adapters import BaseAdapter
ImportError: No module named adapters

**Comment by EDDINE-ZERO** [comment]
Xero»modules»pscan ➮ run

[++] Please wait ... Scanning ports on 192.168.1.20 
nmap: error while loading shared libraries: liblua5.3-lpeg.so.2: cannot open shared object file: No such file or directory     ??????

**Comment by Ziakanon** [comment]
Hi EDDINE-ZERO
Try sudo apt-get install liblua5.3

**Comment by shajahanak** [comment]
python xerosploit.py 
Traceback (most recent call last):
  File "xerosploit.py", line 980, in main
    home()
  File "xerosploit.py", line 62, in home
    config0()
  File "xerosploit.py", line 44, in config0
    up_interface = open('/opt/xerosploit/tools/files/iface.txt', 'r').read()
IOError: [Errno 2] No such file or directory: '/opt/xerosploit/tools/files/iface.txt'

**Comment by weblikerwebhost** [comment]
sudo xerosploit
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables

try all codes above but not yet fixed

**Comment by amexlast** [comment]
TO FIX this Proplem 

 Write this orders 
1.apt-get install python-dev python-setuptools libpcap0.8-dev libnetfilter-queue-dev libssl-dev libjpeg-dev libxml2-dev libxslt1-dev libcapstone3 libcapstone-dev libffi-dev file

2.git clone https://github.com/byt3bl33d3r/MITMf

3.cd MITMf

4.git submodule init

5.git submodule update --recursive

6.pip install -r requirements.txt

7.python mitmf.py --help

8.git clone https://github.com/LionSec/xerosploit

9.cd xerosploit

10.python install.py

11.xerosploit

 And Enjoy Hack FROm MEx Proffsional

**Comment by thiago325** [comment]
I did following all the steps,step by step,but isn't working,always when i type xerosploit it gives me this message:
root@ACA801701:~# xerosploit
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables
root@ACA801701:~#

**Comment by thiago325** [comment]
when i see the line "xerosploit
Traceback (most recent call last):
File "/opt/xerosploit/xerosploit.py", line 26, in 
from terminaltables import DoubleTable"

i think the problem could be in DoubleTable,so i try to put this:
pip install DoubleTable

But it gives me this message:
root@ACA801701:~# pip install DoubleTable
Collecting DoubleTable
  Could not find a version that satisfies the requirement DoubleTable (from versions: )
No matching distribution found for DoubleTable

**Comment by shivachoudhary** [comment]
:~/MITMf# python mitmf.py --help
Traceback (most recent call last):
  File "mitmf.py", line 36, in <module>
    from plugins import *
  File "/root/MITMf/plugins/filepwn.py", line 70, in <module>
    import magic
ImportError: No module named magic

**Comment by Mill0s** [comment]
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables

Same error

**Comment by Mill0s** [comment]
Fixed it, when you are using pip install, make sure you use **sudo pip install**

**Comment by shivachoudhary** [comment]
Yaaaay I cleared this error through just upgraded my host system...

On 01-Feb-2017 4:12 pm, "Mill0s" <notifications@github.com> wrote:

Fixed it, when you are using pip install, make sure you use *sudo pip
install*

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/LionSec/xerosploit/issues/4#issuecomment-276626104>,
or mute
the thread

**Comment by only1help** [comment]
Besides this ... ( Además de esto )
pip install terminaltables
pip install tabulate
Do you have it in the /opt folder? ( lo tenis en la carpeta /opt? )

**Comment by Himanshut504** [comment]
Shivachoudhary can you please give me guidance from initially 
I have followed the same steps as given above but unable to run this

**Comment by dzandroid1** [comment]
There is a problem when i enter login show me message 1 and when or fix the problem show me message 2, knowing all tried commands and solutions and the same message at both times.
----------------------------------------------------
message 1 :
xerosploit
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables
-------------------------------------------------------------
message 2
pip install terminaltables
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3074, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3058, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3087, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 679, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==8.1.2' distribution was not found and is required by the application
------------------------------------
I tried all the commands and solutions mentioned in the top and bottom and Youtube ... and did not succeed please solve another useful secret

**Comment by h4qpkt** [comment]
ERROR

from terminaltables import DoubleTable
ImportError: No module named terminaltables

++++++++++++++++++++++++++++++

FIX

chmod +x ./install.py
./install.py setup

**Comment by Himanshut504** [comment]
Finally it was solved only you have to upgrade your Kali version to 2017.2
xerosploit shall be installed easily...

**Comment by 59y3m** [comment]
u can easily run xerosploit just by copying xerosploit into opt/ folder and a placing a copy on desktop then just run the command (./run.sh) without bracket .then u will get error for terminalables just install them by using ( pip install teminaltables ) after that run the command ( ./run.sh ) now u will get the error no module tabulate to solve this just type in the terminal ( pip install tabulate ) and u r done.

**Comment by Mrvu182hp** [comment]
please help me install xerosploit problem
git clone https://github.com/LionSec/xerosploit.git
fatal: destination path 'xerosploit' already exists and is not an empty directory.

install complete ryb xerosploit not work
oot@kali:~# xerosploit
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables

**Comment by Himanshut504** [comment]
I think you should update your Kali version to get rid from this..

On Feb 6, 2018 16:09, "Mrvu182hp" <notifications@github.com> wrote:

please help me install xerosploit problem
git clone https://github.com/LionSec/xerosploit.git
fatal: destination path 'xerosploit' already exists and is not an empty
directory.

install complete ryb xerosploit not work
oot@kali:~# xerosploit

Traceback (most recent call last):
File "/opt/xerosploit/xerosploit.py", line 26, in
from terminaltables import DoubleTable
ImportError: No module named terminaltables

—

You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LionSec/xerosploit/issues/4#issuecomment-363382298>,
or mute
the thread

**Comment by ModifickGR** [comment]
if u have this error:
root@kali:~/Desktop/xerosploit# python xerosploit.py
Traceback (most recent call last):
  File "xerosploit.py", line 980, in main
    home()
  File "xerosploit.py", line 62, in home
    config0()
  File "xerosploit.py", line 44, in config0
    up_interface = open('/opt/xerosploit/tools/files/iface.txt', 'r').read()
IOError: [Errno 2] No such file or directory: '/opt/xerosploit/tools/files/iface.txt'

JUST MOVE THE xerosploit DIR IN /opt LOCATION... or just edit xerosploit.py code

**Comment by ModifickGR** [comment]
if u have this error:
root@kali:~/Desktop/xerosploit# sudo python xerosploit.py
Traceback (most recent call last):
  File "xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables

TRY (pip install terminaltables) OR (sudo pip install terminaltables)

**Comment by ModifickGR** [comment]
if u have this error:
root@kali:~/Desktop/xerosploit# sudo python xerosploit.py
Traceback (most recent call last):
  File "xerosploit.py", line 27, in <module>
    from tabulate import tabulate
ImportError: No module named tabulate

TRY (pip install tabulate) or (sudo pip install tabulate)

**Comment by classer12271227** [comment]
Traceback (most recent call last):
  File "./xerosploit.py", line 980, in main
    home()
  File "./xerosploit.py", line 62, in home
    config0()
  File "./xerosploit.py", line 44, in config0
    up_interface = open('/opt/xerosploit/tools/files/iface.txt', 'r').read()
IOError: [Errno 2] No such file or directory: '/opt/xerosploit/tools/files/iface.txt'


I want to install xerosploit in kali linux 2017.2.
How can I fix this problem?
please help me!!

**Comment by ModifickGR** [comment]
#classer12271227
i have the solution up...just move the xerosploit dir into the /opt folder

**Comment by classer12271227** [comment]
Oh it works perfectly!! Thank you very much!!!

**Comment by Adeka-UAR** [comment]
to fix it : 
just use "sudo" before each "pip install" command since needs to use "sudo xerosploit" to run it.

**Comment by hamouda1** [comment]
try
1.sudo pip install python

2.sudo pip install python2
3.git clone https://github.com/LionSec/xerosploit
4.cd xerosploit
5.python install.py or ./install.sh
6.python xerosploit.py or ./xerosploit.py

**Comment by Hassanxxx** [comment]
I have experienced this problem since morning

root @ kali: ~ / Desktop / xerosploit # sudo python xerosploit.py
Traceback (most recent call last):
File "xerosploit.py", line 27, in
from tabulate import tabulate
ImportError: No module named Tiling

And now after five hours have been resolved and ordered only one that is:
sudo pip install python

Thank you

**Comment by Danikrlop47** [comment]
guys before running ./install.py use chmod +x install.py

**Comment by mdjihadparvez** [comment]
Traceback (most recent call last):
  File "xerosploit.py", line 27, in <module>
    from tabulate import tabulate
ImportError: No module named tabulate


Help Me.......

**Comment by mdjihadparvez** [comment]
File "/opt/xerosploit/xerosploit.py", line 980, in main
    home()

**Comment by Cryp70n1c-W45p** [comment]
haha Here is solution
Install your requirement in root,

command > su
enter password
pip install missing module
xerosploit

**Comment by jisjose98** [comment]
run using python3 xerosploit.oy

**Comment by imshambhav** [comment]
100 percent guaranteed SOLUTION:
TRY THIS

 sudo apt-get install 2to3

 sudo pip install 2to3
 sudo 2to3 
 sudo 2to3 -w xerosploit.py

 sudo python3 xerosploit.py
