### ISSUE TITLE
Xero Module Replace - not working

### ISSUE THREAD

**Issue by xanhacks** [LionSec/xerosploit#42]
**# error:**
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/opt/xerosploit/xerosploit.py", line 869, in cmd0
    scan()
  File "/opt/xerosploit/xerosploit.py", line 129, in scan
    target_ip()
  File "/opt/xerosploit/xerosploit.py", line 855, in target_ip
    program0()
  File "/opt/xerosploit/xerosploit.py", line 829, in program0
    option()
  File "/opt/xerosploit/xerosploit.py", line 635, in option
    replace()
  File "/opt/xerosploit/xerosploit.py", line 621, in replace
    from PIL import Image
ImportError: No module named PIL

Please help me !

**Comment by HudsonSeiler** [comment]
I also have the an issue that crashes xerosploit on the current VM-Ware image of Kali-Linux-2016.2-vm-amd64 
https://images.offensive-security.com/virtual-images/Kali-Linux-2016.2-vm-amd64.7z

Xero»modules»replace ➮ '/root/Pictures/dead.jpg' 
Traceback (most recent call last):
File "/opt/xerosploit/xerosploit.py", line 981, in main
cmd0()
File "/opt/xerosploit/xerosploit.py", line 871, in cmd0
target_ip()
File "/opt/xerosploit/xerosploit.py", line 855, in target_ip
program0()
File "/opt/xerosploit/xerosploit.py", line 829, in program0
option()
File "/opt/xerosploit/xerosploit.py", line 825, in option
option()
File "/opt/xerosploit/xerosploit.py", line 635, in option
replace()
File "/opt/xerosploit/xerosploit.py", line 622, in replace
img = Image.open(img_replace)
File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2280, in open
fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '/root/Pictures/dead.jpg '

Please help me

**Comment by ahmedkhan** [comment]
/usr/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate': undefined method `activate' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /var/lib/gems/2.3.0/gems/xettercap-1.5.7xerob/bin/xettercap:16:in `<top (required)>'
	from /usr/local/bin/xettercap:22:in `load'
	from /usr/local/bin/xettercap:22:in `<main>'

**Comment by Underbrine** [comment]
you need to install python-imaging library
