### ISSUE TITLE
I have problem with run Xerosploit please help me 

### ISSUE THREAD

**Issue by hawraz93** [LionSec/xerosploit#54]
/var/lib/gems/2.3.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:24:in `<class:ICMPRedirectPacket>': uninitialized constant PacketFu::EthHeaderMixin (NameError)
	from /var/lib/gems/2.3.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:17:in `<module:Spoofers>'
	from /var/lib/gems/2.3.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:15:in `<module:BetterCap>'
	from /var/lib/gems/2.3.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:14:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:66:in `block in bettercap_autoload'
	from /var/lib/gems/2.3.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:65:in `each'
	from /var/lib/gems/2.3.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:65:in `bettercap_autoload'
	from /var/lib/gems/2.3.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:70:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/xettercap-1.5.7xerob/bin/xettercap:16:in `<top (required)>'
	from /usr/local/bin/xettercap:23:in `load'
	from /usr/local/bin/xettercap:23:in `<main>'

**Comment by johardada** [comment]
i had same problem
try 
apt-get install bettercap 
it worked for me

**Comment by yizhimanpadewoniu** [comment]
I have the same problem by using the tools, maybe i make some mistakes ?

**Comment by moose816a** [comment]
run these commands
sudo apt-get upgrade && apt-get update
sudo apt-get dist-upgrade
gem install bettercap
apt-get install bettercap
install all bettercap dependencies google bettercap installation
it should resolve the issue

**Comment by ansarid** [comment]
You need to install PacketFu version 1.1.11 using:
`sudo gem install packetfu -v 1.1.11`

**Comment by robbytakdirillah** [comment]
Traceback (most recent call last):
	3: from /usr/local/bin/xettercap:23:in `<main>'
	2: from /usr/local/bin/xettercap:23:in `load'
	1: from /var/lib/gems/2.5.0/gems/xettercap-1.5.7xerob/bin/xettercap:24:in `<top (required)>'
/var/lib/gems/2.5.0/gems/xettercap-1.5.7xerob/bin/xettercap:51:in `rescue in <top (required)>': undefined local variable or method `original_argv' for main:Object (NameError)
help @ansarid

**Comment by ansarid** [comment]
> Traceback (most recent call last):
> 3: from /usr/local/bin/xettercap:23:in `<main>' 2: from /usr/local/bin/xettercap:23:in`load'
> 1: from /var/lib/gems/2.5.0/gems/xettercap-1.5.7xerob/bin/xettercap:24:in `<top (required)>' /var/lib/gems/2.5.0/gems/xettercap-1.5.7xerob/bin/xettercap:51:in`rescue in <top (required)>': undefined local variable or method `original_argv' for main:Object (NameError)
> help @ansarid

What is this? You just pasted the output of an error with zero context as to what you did to get this error. No way for me to reproduce this or even understand the issue if you are going to just paste the output of an error without any context and put "help @ansarid". Also don't then go paste this useless comment to all the other places I have helped people. Open up your own issue where people can help you.

Now if you want real help, tell us what you did to get this error, what fixes you attempeted, how they changed the output if at all, and then maybe I can help you fix your issue.

**Comment by Ubunkali** [comment]
Noob here I install xerosploit onto Ubuntu newest edition when running (yplay) this is the error I got any help would sincerely be appreciated.
Traceback (most recent call last):
	3: from /usr/local/bin/xettercap:23:in `<main>'
	2: from /usr/local/bin/xettercap:23:in `load'
	1: from /var/lib/gems/2.5.0/gems/xettercap-1.5.7xerob/bin/xettercap:24:in `<top (required)>'
/var/lib/gems/2.5.0/gems/xettercap-1.5.7xerob/bin/xettercap:51:in `rescue in <top (required)>': undefined local variable or method `original_argv' for main:Object (NameError)
