### ISSUE TITLE
Deface error help!!!!

### ISSUE THREAD

**Issue by Defalt2** [LionSec/xerosploit#56]
Xero»modules»deface ➮ run

[+] Specify the file containing your defacement code .

[!] Your file should not contain Javascript code .

Xero»modules»deface ➮ '/home/reset/Downloads/Njay.html' 

[++] Overwriting all web pages ... 

[++] Press 'Ctrl + C' to stop . 

Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/opt/xerosploit/xerosploit.py", line 869, in cmd0
    scan()
  File "/opt/xerosploit/xerosploit.py", line 129, in scan
    target_ip()
  File "/opt/xerosploit/xerosploit.py", line 855, in target_ip
    program0()
  File "/opt/xerosploit/xerosploit.py", line 829, in program0
    option()
  File "/opt/xerosploit/xerosploit.py", line 784, in option
    deface()
  File "/opt/xerosploit/xerosploit.py", line 774, in deface
    f1 = open('/home/home/xero-html.html','w')
IOError: [Errno 2] No such file or directory: '/home/home/xero-html.html'

**Comment by bat553** [comment]
Same problem here

**Comment by Darkdias** [comment]
Hey guys, go in opt/xerosploit/xerosploit.py and search /home/home, modify it in /home/username
