### ISSUE TITLE
please fix !!

### ISSUE THREAD

**Issue by sidhant07** [LionSec/xerosploit#57]
[+] Enter 'run' to execute the 'move' command.

Xero»modules»shakescreen ➮ run

[++] Injecting shakescreen.js  ... 

[++] Press 'Ctrl + C' to stop . 

/var/lib/gems/2.2.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:24:in `<class:ICMPRedirectPacket>': uninitialized constant PacketFu::EthHeaderMixin (NameError)
	from /var/lib/gems/2.2.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:17:in `<module:Spoofers>'
	from /var/lib/gems/2.2.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:15:in `<module:BetterCap>'
	from /var/lib/gems/2.2.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:14:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /var/lib/gems/2.2.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:66:in `block in bettercap_autoload'
	from /var/lib/gems/2.2.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:65:in `each'
	from /var/lib/gems/2.2.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:65:in `bettercap_autoload'
	from /var/lib/gems/2.2.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:70:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /var/lib/gems/2.2.0/gems/xettercap-1.5.7xerob/bin/xettercap:16:in `<top (required)>'
	from /usr/local/bin/xettercap:23:in `load'
	from /usr/local/bin/xettercap:23:in `<main>'

[+] Enter 'run' to execute the 'move' command.

Xero»modules»shakescreen ➮

**Comment by xufucun** [comment]
sudo gem uninstall packetfu
sudo gem install packetfu -v 1.1.11
