### ISSUE TITLE
i need help as i am getting this error again and again when i try to any command on xerosploit

### ISSUE THREAD

**Issue by rishabhrsjain** [LionSec/xerosploit#59]
/var/lib/gems/2.3.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:24:in `<class:ICMPRedirectPacket>': uninitialized constant PacketFu::EthHeaderMixin (NameError)
	from /var/lib/gems/2.3.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:17:in `<module:Spoofers>'
	from /var/lib/gems/2.3.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:15:in `<module:BetterCap>'
	from /var/lib/gems/2.3.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:14:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:66:in `block in bettercap_autoload'
	from /var/lib/gems/2.3.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:65:in `each'
	from /var/lib/gems/2.3.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:65:in `bettercap_autoload'
	from /var/lib/gems/2.3.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:70:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /var/lib/gems/2.3.0/gems/xettercap-1.5.7xerob/bin/xettercap:16:in `<top (required)>'
	from /usr/local/bin/xettercap:23:in `load'
	from /usr/local/bin/xettercap:23:in `<main>'

**Comment by Martou1** [comment]
Same as me...

**Comment by tanmayag98** [comment]
Same here :(

**Comment by Martou1** [comment]
Amazing, thank you verymuch @tanmayag98 !

**Comment by ansarid** [comment]
You need to install PacketFu version 1.1.11 using:
`sudo gem install packetfu -v 1.1.11`

**Comment by samiyounis** [comment]
root@Root:~# xerosploit
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables



could someone help me please!!!!
@ansarid

**Comment by ansarid** [comment]
@samiyounis sudo pip install terminaltables

**Comment by robbytakdirillah** [comment]
Traceback (most recent call last):
	3: from /usr/local/bin/xettercap:23:in `<main>'
	2: from /usr/local/bin/xettercap:23:in `load'
	1: from /var/lib/gems/2.5.0/gems/xettercap-1.5.7xerob/bin/xettercap:24:in `<top (required)>'
/var/lib/gems/2.5.0/gems/xettercap-1.5.7xerob/bin/xettercap:51:in `rescue in <top (required)>': undefined local variable or method `original_argv' for main:Object (NameError)
help  @ansarid

**Comment by ansarid** [comment]
> Traceback (most recent call last):
> 3: from /usr/local/bin/xettercap:23:in `<main>' 2: from /usr/local/bin/xettercap:23:in`load'
> 1: from /var/lib/gems/2.5.0/gems/xettercap-1.5.7xerob/bin/xettercap:24:in `<top (required)>' /var/lib/gems/2.5.0/gems/xettercap-1.5.7xerob/bin/xettercap:51:in`rescue in <top (required)>': undefined local variable or method `original_argv' for main:Object (NameError)
> help @ansarid

What is this? You just pasted the output of an error with zero context as to what you did to get this error. No way for me to reproduce this or even understand the issue if you are going to just paste the output of an error without any context and put "help @ansarid". Also don't then go paste this useless comment to all the other places I have helped people. Open up your own issue where people can help you.

Now if you want real help, tell us what you did to get this error, what fixes you attempted, how they changed the output if at all, and then maybe I can help you fix your issue.

**Comment by githubbish** [comment]
Hello.
I need help here, please. Installed xerosploit as usual, wanted to use sniff command and got errors. All dependancies were up to date.

Followed the answers here about bettercap and deleted in gems directory:
```
/var/lib/gems/2.5.0/gems/bettercap-1.6.*
/var/lib/gems/2.5.0/gems/packetfu-1.1*
```
Installed packetfu by: `gem install packetfu -v 1.1.11`
can't use command: `gem build bettercap.gemspec` because gamespec file wasn't found.
So i installed bettercap by: `sudo gem install bettercap`

Previous errors (can't remember which ones but similiar to those in previous posts here) aren't here anymore. But in 2nd terminal where were these errors before i got now blank, black screen. In the main terminal got:

> Traceback (most recent call last):
> 	8: from /usr/local/bin/xettercap:23:in `<main>'
> 	7: from /usr/local/bin/xettercap:23:in `load'
> 	6: from /var/lib/gems/2.5.0/gems/xettercap-1.5.7xerob/bin/xettercap:16:in `<top (required)>'
> 	5: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
> 	4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
> 	3: from /var/lib/gems/2.5.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:29:in `<top (required)>'
> 	2: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
> 	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
> /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- packetfu (LoadError)
> 

Someone can help me out there, please? Where i'm doing wrong steps?

**Comment by githubbish** [comment]
Ok. I done this, guys. If you get these all problems after you installed xerosploit, the best will be to erase all and start it from the scratch again. Check here: `/etc/apt/sources.list
` what resources you got. Should be like these in this link: https://docs.kali.org/general-use/kali-linux-sources-list-repositories

So then do this first line by line as i did:

```
rm -rf /opt/xerosploit/
sudo apt-get upgrade && apt-get update
sudo apt-get dist-upgrade
sudo gem install bettercap
sudo apt-get install bettercap
```

And AFTER that you have to remember to uninstall ALL installed previously versions of packetfu and then install it again in specific version:

```
sudo gem uninstall packetfu
sudo gem install packetfu -v 1.1.11
cd xerosploit
sudo python install.py
```
Then start xerosploit and there you go!

Damn, that was time eater :) Next time just collect the information from all sources and think by yourself. Do not ask everyone in every thread about the same :)
