### ISSUE TITLE
Need Help!! Whenever i run the Xerosploit This happened everytime.

### ISSUE THREAD

**Issue by khanfurman** [LionSec/xerosploit#62]
/var/lib/gems/2.2.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:24:in `<class:ICMPRedirectPacket>': uninitialized constant PacketFu::EthHeaderMixin (NameError)
	from /var/lib/gems/2.2.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:17:in `<module:Spoofers>'
	from /var/lib/gems/2.2.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:15:in `<module:BetterCap>'
	from /var/lib/gems/2.2.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:14:in `<top (required)>'
	from /usr/local/lib/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.2.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:66:in `block in bettercap_autoload'
	from /var/lib/gems/2.2.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:65:in `each'
	from /var/lib/gems/2.2.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:65:in `bettercap_autoload'
	from /var/lib/gems/2.2.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:70:in `<top (required)>'
	from /usr/local/lib/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /var/lib/gems/2.2.0/gems/xettercap-1.5.7xerob/bin/xettercap:16:in `<top (required)>'
	from /usr/local/bin/xettercap:23:in `load'
	from /usr/local/bin/xettercap:23:in `<main>'

**Comment by xufucun** [comment]
sudo gem uninstall packetfu
sudo gem install packetfu -v 1.1.11

**Comment by khanfurman** [comment]
Now I am getting this

root@kali:~# sudo gem uninstall packetfu
ERROR:  While executing gem ... (Gem::InstallError)
    packetfu is not installed in GEM_HOME, try:
	gem uninstall -i /usr/share/rubygems-integration/all packetfu
root@kali:~# gem uninstall -i /usr/share/rubygems-integration/all packetfu


You have requested to uninstall the gem:
	packetfu-1.1.11

bettercap-1.6.0 depends on packetfu (>= 1.1.10, ~> 1.1)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  ERROR:  While executing gem ... (Gem::DependencyRemovalException)
    Uninstallation aborted due to dependent gem(s)

**Comment by khanfurman** [comment]
and this 
root@kali:~# sudo gem install packetfu -v 1.1.11
ERROR:  Loading command: install (LoadError)
	/usr/lib/x86_64-linux-gnu/ruby/2.3.0/openssl.so: symbol SSLv2_method, version OPENSSL_1.0.2d not defined in file libssl.so.1.0.2 with link time reference - /usr/lib/x86_64-linux-gnu/ruby/2.3.0/openssl.so
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass

**Comment by ansarid** [comment]
You need to install PacketFu version 1.1.11 using:
`sudo gem install packetfu -v 1.1.11`

**Comment by ahmedkhan** [comment]
/usr/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate': undefined method `activate' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /var/lib/gems/2.3.0/gems/xettercap-1.5.7xerob/bin/xettercap:16:in `<top (required)>'
	from /usr/local/bin/xettercap:22:in `load'
	from /usr/local/bin/xettercap:22:in `<main>'
