### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by tobadev** [LionSec/xerosploit#7]
Hai, i'm getting random type of errors while i try to run any module
Example of sniff module error:
`/var/lib/gems/2.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:24:in `<class:ICMPRedirectPacket>': uninitialized constant PacketFu::EthHeaderMixin (NameError)
	from /var/lib/gems/2.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:17:in `<module:Spoofers>'
	from /var/lib/gems/2.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:15:in `<module:BetterCap>'
	from /var/lib/gems/2.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:14:in `<top (required)>'
	from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:66:in `block in bettercap_autoload'
	from /var/lib/gems/2.1.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:65:in `each'
	from /var/lib/gems/2.1.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:65:in `bettercap_autoload'
	from /var/lib/gems/2.1.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:70:in `<top (required)>'
	from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /var/lib/gems/2.1.0/gems/xettercap-1.5.7xerob/bin/xettercap:16:in `<top (required)>'
	from /usr/local/bin/xettercap:23:in `load'
	from /usr/local/bin/xettercap:23:in `<main>'

`
I updated ruby gems btw so no idea whats going on

**Comment by ansarid** [comment]
Got the same problem, no idea.

**Comment by ansarid** [comment]
You need to install PacketFu version 1.1.11 using:
`sudo gem install packetfu -v 1.1.11`
