### ISSUE TITLE
Execute error

### ISSUE THREAD

**Issue by behnam10** [LionSec/xerosploit#72]
Traceback (most recent call last):
  File "./xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables

**Comment by samupert** [comment]
Try this 

`apt-get install tabulate `
`apt-get install terminaltables`

then 

`pip install terminaltables`
`pip install tabulate`

Worked for me.
Cheers

**Comment by arismelachroinos** [comment]
I have the same issue. Solution above didnt help

**Comment by Liljhon241** [comment]
To Fix File "/opt/xerosploit/xerosploit.py", line 26, in <module> from terminaltables import DoubleTable ImportError: No module named terminaltables After installing terminaltables and tabulate by running pip install terminaltables and pip install tabulate go to /usr/local/lib/python3.5/dist-packages copy and paste terminaltables and tabulate in the xerosploit directory then run xerosploit in the terminal (sorry for my bad english)
