### ISSUE TITLE
xerosploit not run replace

### ISSUE THREAD

**Issue by almakhzumi** [LionSec/xerosploit#73]
hei, how can fix it this problem :
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/opt/xerosploit/xerosploit.py", line 871, in cmd0
    target_ip()
  File "/opt/xerosploit/xerosploit.py", line 855, in target_ip
    program0()
  File "/opt/xerosploit/xerosploit.py", line 829, in program0
    option()
  File "/opt/xerosploit/xerosploit.py", line 635, in option
    replace()
  File "/opt/xerosploit/xerosploit.py", line 621, in replace
    from PIL import Image
ImportError: No module named PIL

**Comment by Ananchowdhury** [comment]
how can i fix this problem:
 
Traceback (most recent call last):
  File "xerosploit.py", line 980, in main
    home()
  File "xerosploit.py", line 62, in home
    config0()
  File "xerosploit.py", line 44, in config0
    up_interface = open('/opt/xerosploit/tools/files/iface.txt', 'r').read()
IOError: [Errno 2] No such file or directory: '/opt/xerosploit/tools/files/iface.txt'
