### ISSUE TITLE
Xerosploit not working

### ISSUE THREAD

**Issue by ItzL3op4rd** [LionSec/xerosploit#77]
I have installed correctly all the dependencies

**Comment by ItzL3op4rd** [comment]
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables

**Comment by usama7628674** [comment]
just type this in terminal 
pip install terminaltables

let me know if this works?

**Comment by ItzL3op4rd** [comment]
root@kali:~# pip install terminaltables
Requirement already satisfied: terminaltables in /usr/local/lib/python3.5/dist-packages

**Comment by usama7628674** [comment]
Now install this
pip install tabulate
OR
Try to download them directly from here : https://pypi.python.org/pypi/terminaltables , https://pypi.python.org/pypi/tabulate

During installation select kali (if you are using kali linux) or parrot os (if you are using parrot os)

Which python version are you using?
Make sure you have kali rolling 2017.1 is installed and updated.

**Comment by usama7628674** [comment]
Requirement already satisfied: terminaltables in /usr/local/lib/python3.5/dist-packages
From here I can see it's python 3.5.Make sure you have python 2.7 installed or reinstall it.

**Comment by ItzL3op4rd** [comment]
I have uninstalled python 3.5 and installed 2.7.13
when i type pip:
pip
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/# python3.5/dist-packages/pkg_resources/__init__.py", line 3037, in <module>
    @_call_aside
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3021, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3050, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 969, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 855, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==9.0.1' distribution was not found and is required by the application

**Comment by usama7628674** [comment]
please install pip distribution and python 3 not 3.5

**Comment by usama7628674** [comment]
You need to have both python 2.7 and 3 installed.

**Comment by usama7628674** [comment]
To install pip, securely download get-pip.py.
https://bootstrap.pypa.io/get-pip.py
Then run the following:

python get-pip.py

**Comment by larry852** [comment]
Try:
python2.7 /usr/bin/pip install terminaltables

**Comment by khaledal** [comment]
@larry852 thank you for the help your methode work like let ;)

**Comment by shoa1b** [comment]
@larry852 
python2.7 /usr/bin/pip install terminaltables
python2.7 /usr/bin/pip install tabulate
python2.7 /opt/xerosploit/xerosploit.py

can you please elaborate this method.

**Comment by tajrahman1** [comment]
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/opt/xerosploit/xerosploit.py", line 973, in cmd0
    print(table.table)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-76: ordinal not in range(128)  just showing this problem.. please help me

**Comment by AyEtAnas** [comment]
I fixed this problem by just typing  **sudo pip2 install terminaltables**
If it worked for me it should work for you :)

**Comment by Frenixraj** [comment]
I have installed kali linux in vmware player and installed xerosploit.When the scan is complete it is showing only my device and vmware but not all devices connected to my network.

Pls help me!

**Comment by AbdulConsole** [comment]
> @larry852
> python2.7 /usr/bin/pip install terminaltables
> python2.7 /usr/bin/pip install tabulate
> python2.7 /opt/xerosploit/xerosploit.py
> 
> can you please elaborate this method.



sudo pip2 install tabulate
sudo pip2 install terminaltables

execute the **two commands** above

**Comment by Ralphacan** [comment]
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/opt/xerosploit/xerosploit.py", line 866, in cmd0
    cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip()
NameError: name 'raw_input' is not defined

That the error i got

**Comment by AnonymousNik** [comment]
> Traceback (most recent call last):
> File "/opt/xerosploit/xerosploit.py", line 981, in main
> cmd0()
> File "/opt/xerosploit/xerosploit.py", line 866, in cmd0
> cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip()
> NameError: name 'raw_input' is not defined
> 
> That the error i got

Updated versions of python don't allow raw_input(),
replace raw_input() with input() 
or
Install python --version 1 by typing following commands :
sudo apt install python

**Comment by daringvulture** [comment]
error not solved ( DoubleTable )

**Comment by daringvulture** [comment]
I have installed correctly all the dependencies
Traceback (most recent call last):
File "/opt/xerosploit/xerosploit.py", line 26, in
from terminaltables import DoubleTable
ImportError: No module named terminaltables

**Comment by delloufia** [comment]
> I have installed correctly all the dependencies
> Traceback (most recent call last):
> File "/opt/xerosploit/xerosploit.py", line 26, in
> from terminaltables import DoubleTable
> ImportError: No module named terminaltables

Hi, did you tried to install terminaltables with pip command?

pip install terminaltables

It must work :)

**Comment by daringvulture** [comment]
Yes

**Comment by daringvulture** [comment]
> > I have installed correctly all the dependencies
> > Traceback (most recent call last):
> > File "/opt/xerosploit/xerosploit.py", line 26, in
> > from terminaltables import DoubleTable
> > ImportError: No module named terminaltables
> 
> Hi, did you tried to install terminaltables with pip command?
> 
> pip install terminaltables
> 
> It must work :)

Yes I have tried it

**Comment by rocko2020** [comment]
I am facing the same problem. Guys do u have any solution?
Pls, help.

**Comment by Niteshsahni** [comment]
Traceback (most recent call last):
  File "xerosploit.py", line 981, in main
    cmd0()
  File "xerosploit.py", line 866, in cmd0
    cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip()
NameError: name 'raw_input' is not defined

**Comment by delloufia** [comment]
> Traceback (most recent call last):
> File "xerosploit.py", line 981, in main
> cmd0()
> File "xerosploit.py", line 866, in cmd0
> cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip()
> NameError: name 'raw_input' is not defined

Hi @Niteshsahni , 

`NameError: name 'raw_input' is not defined` means that you're using python3 instead of python2. So use python2 and the script must work

**Comment by TaoMonLae** [comment]
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables

I tried everything on the above but still having the problem

**Comment by HyperionLearner** [comment]
**This works perfectly for me....**

```
/usr/bin/python -m pip install --upgrade pip
pip2 install setuptools
pip2 install terminaltables
pip2 install tabulate

```

**Comment by PlanetDestroyyer** [comment]
You should install python packages in root env i.e. with sudo


`sudo pip install terminaltables  tabulate` 

if using arch based distro or arch then do 

`sudo pip install terminaltables  tabulate --break-system-packages` 
if only u r so much eager to do else create one new env and then do
