### ISSUE TITLE
bettercap Error gem 

### ISSUE THREAD

**Issue by GoldenHex** [LionSec/xerosploit#8]
![wa3](https://cloud.githubusercontent.com/assets/8321366/17459860/6a5d3128-5c3b-11e6-931f-182091ed49d1.png)

**Comment by miguelebf** [comment]
I have the same problem

**Comment by thinksabin** [comment]
same here:

/var/lib/gems/2.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:24:in `<class:ICMPRedirectPacket>': uninitialized constant PacketFu::EthHeaderMixin (NameError)
	from /var/lib/gems/2.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:17:in `<module:Spoofers>'
	from /var/lib/gems/2.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:15:in `<module:BetterCap>'
	from /var/lib/gems/2.1.0/gems/xettercap-1.5.7xerob/lib/bettercap/spoofers/icmp.rb:14:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:66:in `block in bettercap_autoload'
	from /var/lib/gems/2.1.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:65:in `each'
	from /var/lib/gems/2.1.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:65:in `bettercap_autoload'
	from /var/lib/gems/2.1.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:70:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/xettercap-1.5.7xerob/bin/xettercap:16:in `<top (required)>'
	from /usr/local/bin/xettercap:23:in `load'
	from /usr/local/bin/xettercap:23:in `<main>'

**Comment by THXMASTER** [comment]
i get exactly the same error in my kali linux install in vm. any fix coming soon?

**Comment by d4rkn0** [comment]
+ update apt source repositories ( disable sana repository & add rolling repository)
root@unknown:/home/d4rkn0# vim /etc/apt/sources.list
deb http://http.kali.org/kali kali-rolling main contrib non-free
#deb http://old.kali.org/kali sana main non-free contrib

+ upgrade ruby-dev to 2.3
apt-get upgrade ruby-dev

d4rkn0@unknown:~$ ruby -v
ruby 2.3.1p112 (2016-04-26)

+ remove old xerpsploit
rm -rf /opt/xerosploit

+ reinstall xerosploit
git clone https://github.com/LionSec/xerosploit
cd xerosploit && sudo python install.py
sudo xerosploit

( i got some problem after upgrade

**Comment by ansarid** [comment]
You need to install PacketFu version 1.1.11 using:
`sudo gem install packetfu -v 1.1.11`
