### ISSUE TITLE
Not working on parrot OS 3.7

### ISSUE THREAD

**Issue by Shubhaxo7** [LionSec/xerosploit#82]
sir i am using parrot OS 3.7 
after all installation complete showing some error like below:

*("Successfully installed xettercap-1.5.7xerob
Parsing documentation for xettercap-1.5.7xerob
Installing ri documentation for xettercap-1.5.7xerob
Done installing documentation for xettercap after 8 seconds
1 gem installed
Xerosploit has been sucessfuly instaled. Execute 'xerosploit' in your terminal.
┌─[root@parrot]─[~/xerosploit]
└──╼ #xerosploit
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables")*

_please help me how to solve this problem._
Thank you

**Comment by usama7628674** [comment]
Just type this in terminal
pip install terminaltables

**Comment by usama7628674** [comment]
If it says no module named (any name) type this in terminal
pip install (name of module)

**Comment by Shubhaxo7** [comment]
Sir Thank Yor your Reply
i have install Xerosploit From Your Realese Version And its Work
Successfully.
You Did Great job By Xerosploit.
Heartly Thanks For Your Work.

**Comment by 04patrick** [comment]
Hello sir
although I have installed the module it always gives me this message

Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables
