### ISSUE TITLE
Error on ubuntu 17.04

### ISSUE THREAD

**Issue by AndreaSau** [LionSec/xerosploit#84]
When i run every module the program crashes:

[+] Enter 'run' to execute the 'replace' command.

Xero»modules»replace ➮ run

[+] Insert your image path. (e.g. /home/capitansalami/pictures/fun.png)

Xero»modules»replace ➮ '/home/andrea/x.jpg' 
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/opt/xerosploit/xerosploit.py", line 869, in cmd0
    scan()
  File "/opt/xerosploit/xerosploit.py", line 129, in scan
    target_ip()
  File "/opt/xerosploit/xerosploit.py", line 855, in target_ip
    program0()
  File "/opt/xerosploit/xerosploit.py", line 829, in program0
    option()
  File "/opt/xerosploit/xerosploit.py", line 825, in option
    option()
  File "/opt/xerosploit/xerosploit.py", line 635, in option
    replace()
  File "/opt/xerosploit/xerosploit.py", line 621, in replace
    from PIL import Image
ImportError: No module named PIL

**Comment by usama7628674** [comment]
It seems that you don't have PIL module installed type this
pip install PIL

**Comment by AndreaSau** [comment]
andrea@andreaUbuntu:~$ pip install pil
Collecting pil
  Could not find a version that satisfies the requirement pil (from versions: )
No matching distribution found for pil
andrea@andreaUbuntu:~$
