### ISSUE TITLE
XeroSploit is not running REPLACE

### ISSUE THREAD

**Issue by MeanMachine123** [LionSec/xerosploit#95]
Xero»modules»replace ➮ run

[+] Insert your image path. (e.g. /home/capitansalami/pictures/fun.png)

Xero»modules»replace ➮ /root/Desktop/87.jpg
Traceback (most recent call last):
  File "xerosploit.py", line 981, in main
    cmd0()
  File "xerosploit.py", line 869, in cmd0
    scan()
  File "xerosploit.py", line 129, in scan
    target_ip()
  File "xerosploit.py", line 855, in target_ip
    program0()
  File "xerosploit.py", line 829, in program0
    option()
  File "xerosploit.py", line 635, in option
    replace()
  File "xerosploit.py", line 623, in replace
    img.save('/opt/xerosploit/tools/bettercap/modules/tmp/ximage.png')
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1372, in save
    self.load()
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFile.py", line 180, in load
    d = Image._getdecoder(self.mode, d, a, self.decoderconfig)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 375, in _getdecoder
    raise IOError("decoder %s not available" % decoder_name)
IOError: decoder jpeg not available

**Comment by Jinovas** [comment]
Getting same error as of recent

**Comment by fl1rty** [comment]
pip check pil

**Comment by MeanMachine123** [comment]
pip check pil
wafw00f 0.9.3 has requirement beautifulsoup4==4.3.2, but you have beautifulsoup4 4.5.1.
pysnmp 4.3.2 requires pysmi, which is not installed.
jsbeautifier 1.6.4 requires editorconfig, which is not installed.
......

________________________________

**Comment by fl1rty** [comment]
Install the requirements !!!

**Comment by MeanMachine123** [comment]
Dude Same Issue Here       :(:(:(



[+] Enter 'run' to execute the 'replace' command.

Xero»modules»replace ➮ run

[+] Insert your image path. (e.g. /home/capitansalami/pictures/fun.png)

Xero»modules»replace ➮ /root/Desktop/1.png
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/opt/xerosploit/xerosploit.py", line 869, in cmd0
    scan()
  File "/opt/xerosploit/xerosploit.py", line 129, in scan
    target_ip()
  File "/opt/xerosploit/xerosploit.py", line 855, in target_ip
    program0()
  File "/opt/xerosploit/xerosploit.py", line 829, in program0
    option()
  File "/opt/xerosploit/xerosploit.py", line 635, in option
    replace()
  File "/opt/xerosploit/xerosploit.py", line 623, in replace
    img.save('/opt/xerosploit/tools/bettercap/modules/tmp/ximage.png')
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1372, in save
    self.load()
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFile.py", line 180, in load
    d = Image._getdecoder(self.mode, d, a, self.decoderconfig)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 375, in _getdecoder
    raise IOError("decoder %s not available" % decoder_name)
IOError: decoder zip not available


NOW WHAT TO DO....................FURTHER.......................I KNOW I AM CLOSE TO SOLVE........



________________________________

**Comment by whiteanony** [comment]
Same problem here what to do guys help us

**Comment by ROhanpersonalkali** [comment]
GUYS I HAVE NOT problem you mentioned above but that problem 
**┌══════════════════════════════════════════════════════════════┐
█                                                              █
█                          Image Replace                       █
█                                                              █
█        Replace all web pages images with your own one        █
└══════════════════════════════════════════════════════════════┘     

[+] Enter 'run' to execute the 'replace' command.

Xero»modules»replace ➮ run

[+] Insert your image path. (e.g. /home/capitansalami/pictures/fun.png)

Xero»modules»replace ➮ '/root/Desktop/yfyf.jpg' 

[++] All images will be replaced by /root/Desktop/yfyf.jpg

[++] Press 'Ctrl + C' to stop . 

sh: 1: xettercap: not found

[+] Enter 'run' to execute the 'replace' command.

Xero»modules»replace ➮ 
**

**Comment by Mehedi61** [comment]
Hello !
I also faced the same issue.
So, I installed Pillow by executing pip install Pillow.
Then the problem was solved.
I hope this solution will also work for you.
Thanks.

**Comment by anonymousReaper** [comment]
after installing pillow also its the same. any other suggestions?

**Comment by hamzabaloch121** [comment]
yeah its still shoing the same error
