### ISSUE TITLE
xerosploit replace not working :/ Plz Help

### ISSUE THREAD

**Issue by OhSlinky** [LionSec/xerosploit#97]
#7 Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/opt/xerosploit/xerosploit.py", line 869, in cmd0
    scan()
  File "/opt/xerosploit/xerosploit.py", line 129, in scan
    target_ip()
  File "/opt/xerosploit/xerosploit.py", line 855, in target_ip
    program0()
  File "/opt/xerosploit/xerosploit.py", line 829, in program0
    option()
  File "/opt/xerosploit/xerosploit.py", line 825, in option
    option()
  File "/opt/xerosploit/xerosploit.py", line 512, in option
    snif()
  File "/opt/xerosploit/xerosploit.py", line 506, in snif
    snif_sslstrip()
  File "/opt/xerosploit/xerosploit.py", line 495, in snif_sslstrip
    snifflog()
  File "/opt/xerosploit/xerosploit.py", line 481, in snifflog
    snif()
  File "/opt/xerosploit/xerosploit.py", line 415, in snif
    option()
  File "/opt/xerosploit/xerosploit.py", line 825, in option
    option()
  File "/opt/xerosploit/xerosploit.py", line 635, in option
    replace()
  File "/opt/xerosploit/xerosploit.py", line 622, in replace
    img = Image.open(img_replace)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1888, in open
    fp = __builtin__.open(fp, "rb")
IOError: [Errno 2] No such file or directory: '/root/Desktop/123.jpg '

Please help

**Comment by hirmanlurish** [comment]
i have same Error Like U

**Comment by MeanMachine123** [comment]
Same Here.......

**Comment by whiteanony** [comment]
same problen here what to do please anyone help us

**Comment by mamuqeeth786** [comment]
hello guys 
every module in it works perfect ..........
In replace module you have add correct format of image eg: png,jpg,Gif

**>**[+]Enter** 'run' to execute the 'replace' # **command.**
Xero»modules»replace ➮ run

[+] Insert your image path. (e.g. /home/capitansalami/pictures/fun.png)

Xero»modules»replace ➮ /home/picture/funny.png)**
 

if you doesn't add correct format of that image,it will give a python error.
if that error repeats again in replace module try to uninstall all python package and reinstall it

**Comment by ahmedkhan** [comment]
/usr/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate': undefined method `activate' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /var/lib/gems/2.3.0/gems/xettercap-1.5.7xerob/bin/xettercap:16:in `<top (required)>'
	from /usr/local/bin/xettercap:22:in `load'
	from /usr/local/bin/xettercap:22:in `<main>'

**Comment by mamuqeeth786** [comment]
Who's this why you send xerosploit error and can't understand it

**Comment by ahmedkhan** [comment]
i m facing this error when i want to sniff network or do any  module plz help me what should i do to run xerosploit working properly

**Comment by azamet90** [comment]
on me it not gives any error but nothing is working not one module even :dancing_women:
