### ISSUE TITLE
error in Excute

### ISSUE THREAD

**Issue by hirmanlurish** [LionSec/xerosploit#98]
**When I  Write python xerosploit.py**

shows me These Erroes : 

Traceback (most recent call last):
  File "xerosploit.py", line 980, in main
    home()
  File "xerosploit.py", line 62, in home
    config0()
  File "xerosploit.py", line 44, in config0
    up_interface = open('/opt/xerosploit/tools/files/iface.txt', 'r').read()
IOError: [Errno 2] No such file or directory: '/opt/xerosploit/tools/files/iface.txt'

# How Fixed it .  Plz help me

**Comment by vaibhavvvv** [comment]
i have same problem..

**Comment by ROhanpersonalkali** [comment]
**me too please help**
